# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/BlocksScreen/lib/ui/fansPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fansPage(object):
    def setupUi(self, fansPage):
        fansPage.setObjectName("fansPage")
        fansPage.resize(710, 410)
        fansPage.setMinimumSize(QtCore.QSize(710, 410))
        fansPage.setMaximumSize(QtCore.QSize(720, 420))
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=fansPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fp_header_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.fp_header_layout.setContentsMargins(0, 0, 0, 0)
        self.fp_header_layout.setObjectName("fp_header_layout")
        self.fp_header_title = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fp_header_title.setFont(font)
        self.fp_header_title.setStyleSheet("background: transparent; color: white;")
        self.fp_header_title.setObjectName("fp_header_title")
        self.fp_header_layout.addWidget(self.fp_header_title)
        self.fp_header_back_btn = BlocksCustomButton(parent=self.horizontalLayoutWidget)
        self.fp_header_back_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.fp_header_back_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.fp_header_back_btn.setText("")
        self.fp_header_back_btn.setFlat(True)
        self.fp_header_back_btn.setProperty("icon_pixmap", QtGui.QPixmap(":/button_borders/media/btn_icons/back.svg"))
        self.fp_header_back_btn.setObjectName("fp_header_back_btn")
        self.fp_header_layout.addWidget(self.fp_header_back_btn)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=fansPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 691, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.fp_content_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.fp_content_vertical_layout.setContentsMargins(5, 5, 5, 5)
        self.fp_content_vertical_layout.setObjectName("fp_content_vertical_layout")
        self.fp_content_horizonta_layout = QtWidgets.QHBoxLayout()
        self.fp_content_horizonta_layout.setContentsMargins(5, 5, 5, 5)
        self.fp_content_horizonta_layout.setObjectName("fp_content_horizonta_layout")
        self.part_cooling_fan_display = BlocksCustomButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.part_cooling_fan_display.sizePolicy().hasHeightForWidth())
        self.part_cooling_fan_display.setSizePolicy(sizePolicy)
        self.part_cooling_fan_display.setMinimumSize(QtCore.QSize(200, 60))
        self.part_cooling_fan_display.setMaximumSize(QtCore.QSize(200, 60))
        self.part_cooling_fan_display.setText("")
        self.part_cooling_fan_display.setFlat(True)
        self.part_cooling_fan_display.setProperty("icon_pixmap", QtGui.QPixmap(":/temperatures/media/btn_icons/fan.svg"))
        self.part_cooling_fan_display.setObjectName("part_cooling_fan_display")
        self.fp_content_horizonta_layout.addWidget(self.part_cooling_fan_display)
        self.auxiliary_fan_display = BlocksCustomButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auxiliary_fan_display.sizePolicy().hasHeightForWidth())
        self.auxiliary_fan_display.setSizePolicy(sizePolicy)
        self.auxiliary_fan_display.setMinimumSize(QtCore.QSize(200, 60))
        self.auxiliary_fan_display.setMaximumSize(QtCore.QSize(200, 60))
        self.auxiliary_fan_display.setText("")
        self.auxiliary_fan_display.setFlat(True)
        self.auxiliary_fan_display.setProperty("icon_pixmap", QtGui.QPixmap(":/temperatures/media/btn_icons/blower.svg"))
        self.auxiliary_fan_display.setObjectName("auxiliary_fan_display")
        self.fp_content_horizonta_layout.addWidget(self.auxiliary_fan_display)
        self.fp_content_vertical_layout.addLayout(self.fp_content_horizonta_layout)

        self.retranslateUi(fansPage)
        QtCore.QMetaObject.connectSlotsByName(fansPage)

    def retranslateUi(self, fansPage):
        _translate = QtCore.QCoreApplication.translate
        fansPage.setWindowTitle(_translate("fansPage", "Form"))
        self.fp_header_title.setText(_translate("fansPage", "Fans"))
        self.fp_header_back_btn.setProperty("button_type", _translate("fansPage", "icon"))
        self.part_cooling_fan_display.setProperty("button_type", _translate("fansPage", "display"))
        self.auxiliary_fan_display.setProperty("button_type", _translate("fansPage", "display"))
from utils.blocks_button import BlocksCustomButton

