# Form implementation generated from reading ui file 'Blocks_Screen/BlocksScreen/lib/ui/filamentSensorsPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_filament_sensors_page(object):
    def setupUi(self, filament_sensors_page):
        filament_sensors_page.setObjectName("filament_sensors_page")
        filament_sensors_page.resize(710, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(filament_sensors_page.sizePolicy().hasHeightForWidth())
        filament_sensors_page.setSizePolicy(sizePolicy)
        filament_sensors_page.setMinimumSize(QtCore.QSize(710, 410))
        filament_sensors_page.setMaximumSize(QtCore.QSize(720, 420))
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=filament_sensors_page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fs_header_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.fs_header_layout.setContentsMargins(0, 0, 0, 0)
        self.fs_header_layout.setObjectName("fs_header_layout")
        self.fs_page_title = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_page_title.sizePolicy().hasHeightForWidth())
        self.fs_page_title.setSizePolicy(sizePolicy)
        self.fs_page_title.setMinimumSize(QtCore.QSize(300, 60))
        self.fs_page_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fs_page_title.setFont(font)
        self.fs_page_title.setStyleSheet("background: transparent; color: white;")
        self.fs_page_title.setObjectName("fs_page_title")
        self.fs_header_layout.addWidget(self.fs_page_title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fs_back_button = BlocksCustomButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_back_button.sizePolicy().hasHeightForWidth())
        self.fs_back_button.setSizePolicy(sizePolicy)
        self.fs_back_button.setMinimumSize(QtCore.QSize(60, 60))
        self.fs_back_button.setMaximumSize(QtCore.QSize(60, 60))
        self.fs_back_button.setText("")
        self.fs_back_button.setFlat(True)
        self.fs_back_button.setProperty("icon_pixmap", QtGui.QPixmap(":/ui/media/btn_icons/back.svg"))
        self.fs_back_button.setObjectName("fs_back_button")
        self.fs_header_layout.addWidget(self.fs_back_button, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=filament_sensors_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 691, 302))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.fs_content_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.fs_content_layout.setContentsMargins(0, 0, 0, 0)
        self.fs_content_layout.setObjectName("fs_content_layout")
        self.fs_sensors_list = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fs_sensors_list.sizePolicy().hasHeightForWidth())
        self.fs_sensors_list.setSizePolicy(sizePolicy)
        self.fs_sensors_list.setMinimumSize(QtCore.QSize(650, 300))
        self.fs_sensors_list.setMaximumSize(QtCore.QSize(700, 300))
        self.fs_sensors_list.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fs_sensors_list.setStyleSheet("QListWidget{background-color: transparent;}\n"
"\n"
"QLabel{\n"
"color: #ffffff;\n"
"}")
        self.fs_sensors_list.setProperty("showDropIndicator", False)
        self.fs_sensors_list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.fs_sensors_list.setObjectName("fs_sensors_list")
        self.fs_content_layout.addWidget(self.fs_sensors_list, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(filament_sensors_page)
        QtCore.QMetaObject.connectSlotsByName(filament_sensors_page)

    def retranslateUi(self, filament_sensors_page):
        _translate = QtCore.QCoreApplication.translate
        filament_sensors_page.setWindowTitle(_translate("filament_sensors_page", "Form"))
        self.fs_page_title.setText(_translate("filament_sensors_page", "Filament Sensors"))
        self.fs_back_button.setProperty("button_type", _translate("filament_sensors_page", "icon"))
from lib.utils.blocks_button import BlocksCustomButton
