# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/BlocksScreen/lib/ui/option_card.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_option_card(object):
    def setupUi(self, option_card):
        option_card.setObjectName("option_card")
        option_card.resize(200, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(option_card.sizePolicy().hasHeightForWidth())
        option_card.setSizePolicy(sizePolicy)
        option_card.setMinimumSize(QtCore.QSize(200, 300))
        option_card.setMaximumSize(QtCore.QSize(400, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(option_card)
        self.verticalLayout.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.option_icon = BlocksLabel(parent=option_card)
        self.option_icon.setMinimumSize(QtCore.QSize(200, 150))
        self.option_icon.setObjectName("option_icon")
        self.verticalLayout.addWidget(self.option_icon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.line = QtWidgets.QFrame(parent=option_card)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.option_text = QtWidgets.QLabel(parent=option_card)
        self.option_text.setMinimumSize(QtCore.QSize(200, 50))
        self.option_text.setObjectName("option_text")
        self.verticalLayout.addWidget(self.option_text)
        self.continue_button = BlocksCustomButton(parent=option_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_button.sizePolicy().hasHeightForWidth())
        self.continue_button.setSizePolicy(sizePolicy)
        self.continue_button.setMinimumSize(QtCore.QSize(200, 80))
        self.continue_button.setText("")
        self.continue_button.setFlat(True)
        self.continue_button.setProperty("icon_pixmap", QtGui.QPixmap(":/arrow_icons/media/btn_icons/right move axis.svg"))
        self.continue_button.setObjectName("continue_button")
        self.verticalLayout.addWidget(self.continue_button)

        self.retranslateUi(option_card)
        QtCore.QMetaObject.connectSlotsByName(option_card)

    def retranslateUi(self, option_card):
        _translate = QtCore.QCoreApplication.translate
        option_card.setWindowTitle(_translate("option_card", "Frame"))
        self.option_icon.setText(_translate("option_card", "TextLabel"))
        self.option_text.setText(_translate("option_card", "TextLabel"))
        self.continue_button.setProperty("button_type", _translate("option_card", "icon"))

from utils.blocks_button import BlocksCustomButton
from utils.blocks_label import BlocksLabel
