# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/BlocksScreen/lib/ui/systemUpdate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_systemUpdatePanel(object):
    def setupUi(self, systemUpdatePanel):
        systemUpdatePanel.setObjectName("systemUpdatePanel")
        systemUpdatePanel.resize(710, 400)
        systemUpdatePanel.setMinimumSize(QtCore.QSize(710, 400))
        systemUpdatePanel.setMaximumSize(QtCore.QSize(720, 420))
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=systemUpdatePanel)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.su_header_title = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.su_header_title.setMinimumSize(QtCore.QSize(300, 60))
        self.su_header_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.su_header_title.setFont(font)
        self.su_header_title.setStyleSheet("background: transparent; color: white;")
        self.su_header_title.setObjectName("su_header_title")
        self.horizontalLayout.addWidget(self.su_header_title)
        self.su_back_button = BlocksCustomButton(parent=self.horizontalLayoutWidget)
        self.su_back_button.setMinimumSize(QtCore.QSize(60, 60))
        self.su_back_button.setMaximumSize(QtCore.QSize(60, 60))
        self.su_back_button.setFlat(True)
        self.su_back_button.setObjectName("su_back_button")
        self.horizontalLayout.addWidget(self.su_back_button)

        self.retranslateUi(systemUpdatePanel)
        QtCore.QMetaObject.connectSlotsByName(systemUpdatePanel)

    def retranslateUi(self, systemUpdatePanel):
        _translate = QtCore.QCoreApplication.translate
        systemUpdatePanel.setWindowTitle(_translate("systemUpdatePanel", "Form"))
        self.su_header_title.setText(_translate("systemUpdatePanel", "System Update"))
        self.su_back_button.setText(_translate("systemUpdatePanel", "PushButton"))
        self.su_back_button.setProperty("button_type", _translate("systemUpdatePanel", "icon"))
from utils.ui import BlocksCustomButton
