# Form implementation generated from reading ui file '/home/gleb/github/Blocks_Screen/Qt_UI/Blocks_Screen_Lemos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 921, 646))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.layoutWidget)
        self.groupBox.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-bottom-color: rgb(145, 145, 145);\n"
"max-height: 60px;\n"
"padding-right: 40px;")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setStyleSheet("QWidget{\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../../../../../../Desktop/DGUS/BLOCKS_DGUS_R21_V1/27_Icons/19.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setEnabled(True)
        self.pushButton.setStyleSheet("QWidget{\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../../../../../../Desktop/DGUS/BLOCKS_DGUS_R21_V1/27_Icons/20.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(19, 19))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setStyleSheet("QWidget{\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 1)
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.layoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.tabWidget.setBaseSize(QtCore.QSize(100, 100))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    min-width: 90px;\n"
"    max-width: 90px;\n"
"    min-height: 20px;\n"
"    max-height: 98px;\n"
"    background: #000000;\n"
"    text-color: #999999;\n"
"}\n"
"QWidget {background-color: transparent;\n"
"height: 400px;\n"
"background-image: url(:/MainBackground/MEDIA/1st_background.png);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(78, 78))
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_home_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab, icon2, "")
        self.Filament = QtWidgets.QWidget()
        self.Filament.setObjectName("Filament")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.Filament)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 100, 300, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.pushButton_6.setPalette(palette)
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"border:none;\n"
"height: 60px;\n"
"width: 300px;\n"
"background-image-y: 300;\n"
"background-color: yellow;\n"
"}\n"
"QPushButton::!pressed{\n"
"icon: url(:/Filament/MEDIA/2_buttons/filament_menu/LOAD.png);\n"
"background-color: yellow;\n"
"}\n"
"QPushButton::pressed {\n"
"border:none;\n"
"height: 60px;\n"
"width: 300px;\n"
"background-color: transparent;\n"
"}")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Filament/MEDIA/2_buttons/filament_menu/LOAD.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/Filament/MEDIA/2_buttons/filament_menu/LOAD_pressed.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QtCore.QSize(300, 80))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setAutoRepeat(False)
        self.pushButton_6.setAutoExclusive(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_filament.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_filament_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.Filament, icon4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_control.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_control_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_utilities.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap("/home/gleb/github/Blocks_Screen/Qt_UI/../MEDIA/1_icons/main_menu/ICON_utilities_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_3, icon6, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.pushButton.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.pushButton_2.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.pushButton_4.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Filament), _translate("MainWindow", "Filament"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
