# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/Qt_UI/Blocks_Screen_Lemos.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import UI_Resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-image: url(:/MainBackground/MEDIA/1st_background.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 802, 646))
        self.layoutWidget.setObjectName("layoutWidget")
        self.central_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.central_grid.setContentsMargins(0, 0, 0, 0)
        self.central_grid.setObjectName("central_grid")
        self.top_bar = QtWidgets.QGroupBox(parent=self.layoutWidget)
        self.top_bar.setMaximumSize(QtCore.QSize(800, 60))
        self.top_bar.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border:none ;\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"    max-height: 60px;\n"
"}")
        self.top_bar.setObjectName("top_bar")
        self.chamber_temp = QtWidgets.QPushButton(parent=self.top_bar)
        self.chamber_temp.setEnabled(True)
        self.chamber_temp.setGeometry(QtCore.QRect(190, 28, 87, 19))
        self.chamber_temp.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/bugo/github/Blocks_Screen/Qt_UI/../../../../../../Desktop/DGUS/BLOCKS_DGUS_R21_V1/27_Icons/19.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.chamber_temp.setIcon(icon)
        self.chamber_temp.setIconSize(QtCore.QSize(19, 19))
        self.chamber_temp.setCheckable(False)
        self.chamber_temp.setChecked(False)
        self.chamber_temp.setFlat(True)
        self.chamber_temp.setObjectName("chamber_temp")
        self.filament_type_1 = QtWidgets.QPushButton(parent=self.top_bar)
        self.filament_type_1.setEnabled(True)
        self.filament_type_1.setGeometry(QtCore.QRect(581, 9, 44, 19))
        self.filament_type_1.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.filament_type_1.setIcon(icon)
        self.filament_type_1.setIconSize(QtCore.QSize(19, 19))
        self.filament_type_1.setCheckable(False)
        self.filament_type_1.setChecked(False)
        self.filament_type_1.setFlat(True)
        self.filament_type_1.setObjectName("filament_type_1")
        self.hot_bed_temp = QtWidgets.QPushButton(parent=self.top_bar)
        self.hot_bed_temp.setEnabled(True)
        self.hot_bed_temp.setGeometry(QtCore.QRect(190, 9, 87, 19))
        self.hot_bed_temp.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.hot_bed_temp.setIcon(icon)
        self.hot_bed_temp.setIconSize(QtCore.QSize(19, 19))
        self.hot_bed_temp.setCheckable(False)
        self.hot_bed_temp.setChecked(False)
        self.hot_bed_temp.setFlat(True)
        self.hot_bed_temp.setObjectName("hot_bed_temp")
        self.filament_type_2 = QtWidgets.QPushButton(parent=self.top_bar)
        self.filament_type_2.setEnabled(True)
        self.filament_type_2.setGeometry(QtCore.QRect(581, 28, 44, 19))
        self.filament_type_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.filament_type_2.setIcon(icon)
        self.filament_type_2.setIconSize(QtCore.QSize(19, 19))
        self.filament_type_2.setCheckable(False)
        self.filament_type_2.setChecked(False)
        self.filament_type_2.setFlat(True)
        self.filament_type_2.setObjectName("filament_type_2")
        self.nozzle_1_temp = QtWidgets.QPushButton(parent=self.top_bar)
        self.nozzle_1_temp.setEnabled(True)
        self.nozzle_1_temp.setGeometry(QtCore.QRect(321, 9, 99, 19))
        self.nozzle_1_temp.setStyleSheet("#nozzle_1_temp{ \n"
"    image: url(:/General_icons/MEDIA/1_icons/top_bar_icons/nozzle_temp_1.png);\n"
"    image-position: left;\n"
"}")
        self.nozzle_1_temp.setIcon(icon)
        self.nozzle_1_temp.setIconSize(QtCore.QSize(19, 19))
        self.nozzle_1_temp.setCheckable(False)
        self.nozzle_1_temp.setChecked(False)
        self.nozzle_1_temp.setFlat(True)
        self.nozzle_1_temp.setObjectName("nozzle_1_temp")
        self.nozzle_2_temp = QtWidgets.QPushButton(parent=self.top_bar)
        self.nozzle_2_temp.setEnabled(True)
        self.nozzle_2_temp.setGeometry(QtCore.QRect(321, 28, 99, 19))
        self.nozzle_2_temp.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/bugo/github/Blocks_Screen/Qt_UI/../../../../../../Desktop/DGUS/BLOCKS_DGUS_R21_V1/27_Icons/20.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.nozzle_2_temp.setIcon(icon1)
        self.nozzle_2_temp.setIconSize(QtCore.QSize(19, 19))
        self.nozzle_2_temp.setCheckable(False)
        self.nozzle_2_temp.setChecked(False)
        self.nozzle_2_temp.setFlat(True)
        self.nozzle_2_temp.setObjectName("nozzle_2_temp")
        self.blocks_logo = QtWidgets.QLabel(parent=self.top_bar)
        self.blocks_logo.setGeometry(QtCore.QRect(9, 9, 71, 38))
        self.blocks_logo.setStyleSheet("#blocks_logo {\n"
"image: url(:/General_icons/MEDIA/media/graphics/logo_blocks.png);\n"
"}")
        self.blocks_logo.setText("")
        self.blocks_logo.setObjectName("blocks_logo")
        self.nozzle_1 = QtWidgets.QPushButton(parent=self.top_bar)
        self.nozzle_1.setEnabled(True)
        self.nozzle_1.setGeometry(QtCore.QRect(451, 9, 79, 19))
        self.nozzle_1.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.nozzle_1.setIcon(icon)
        self.nozzle_1.setIconSize(QtCore.QSize(19, 19))
        self.nozzle_1.setCheckable(False)
        self.nozzle_1.setChecked(False)
        self.nozzle_1.setFlat(True)
        self.nozzle_1.setObjectName("nozzle_1")
        self.nozzle_2 = QtWidgets.QPushButton(parent=self.top_bar)
        self.nozzle_2.setEnabled(True)
        self.nozzle_2.setGeometry(QtCore.QRect(451, 28, 79, 19))
        self.nozzle_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.nozzle_2.setIcon(icon)
        self.nozzle_2.setIconSize(QtCore.QSize(19, 19))
        self.nozzle_2.setCheckable(False)
        self.nozzle_2.setChecked(False)
        self.nozzle_2.setFlat(True)
        self.nozzle_2.setObjectName("nozzle_2")
        self.wifi_signal = QtWidgets.QPushButton(parent=self.top_bar)
        self.wifi_signal.setEnabled(True)
        self.wifi_signal.setGeometry(QtCore.QRect(720, 20, 44, 19))
        self.wifi_signal.setStyleSheet("QWidget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    selection-background-color: rgb(60, 60, 60);\n"
"    gridline-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(60, 60, 60);\n"
"    selection-color: rgb(60, 60, 60);\n"
"    border-bottom-color: rgb(60, 60, 60);\n"
"}")
        self.wifi_signal.setIcon(icon)
        self.wifi_signal.setIconSize(QtCore.QSize(19, 19))
        self.wifi_signal.setCheckable(False)
        self.wifi_signal.setChecked(False)
        self.wifi_signal.setFlat(True)
        self.wifi_signal.setObjectName("wifi_signal")
        self.chamber_temp.raise_()
        self.hot_bed_temp.raise_()
        self.blocks_logo.raise_()
        self.filament_type_1.raise_()
        self.filament_type_2.raise_()
        self.wifi_signal.raise_()
        self.nozzle_1_temp.raise_()
        self.nozzle_2_temp.raise_()
        self.nozzle_1.raise_()
        self.nozzle_2.raise_()
        self.central_grid.addWidget(self.top_bar, 0, 0, 1, 1)
        self.mainTabWidget = QtWidgets.QTabWidget(parent=self.layoutWidget)
        self.mainTabWidget.setEnabled(True)
        self.mainTabWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.mainTabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.mainTabWidget.setBaseSize(QtCore.QSize(100, 100))
        self.mainTabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.mainTabWidget.setAutoFillBackground(False)
        self.mainTabWidget.setStyleSheet("#mainTabWidget {\n"
"background-image: url(:/MainBackground/MEDIA/1st_background.png);\n"
"height: 360px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    min-width: 90px;\n"
"    max-width: 90px;\n"
"    min-height: 100px;\n"
"    max-height: 200px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton.menu_btn {\n"
"    border-image: url(:/Btn_Backgrounds/MEDIA/media/btn_simple.png) 0 0 0 0 stretch stretch;\n"
"    color: #424242;\n"
"    min-height: 95px;\n"
"    max-height: 95px; \n"
"    min-width: 310px;\n"
"    max-width: 310px;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"\n"
"QPushButton.menu_btn::pressed {\n"
"    border-image: url(:/Btn_Backgrounds/MEDIA/media/btn_simple_PRESSED.png) 0 0 0 0 stretch stretch;\n"
"    color: #8e8d8d;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"\n"
"QLabel.title_text {\n"
"    align-text: center;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 30pt;\n"
"    color: white;\n"
"}")
        self.mainTabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.mainTabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.mainTabWidget.setIconSize(QtCore.QSize(60, 60))
        self.mainTabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.mainTabWidget.setUsesScrollButtons(False)
        self.mainTabWidget.setDocumentMode(True)
        self.mainTabWidget.setTabsClosable(False)
        self.mainTabWidget.setMovable(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.main_stacked_widget = QtWidgets.QStackedWidget(parent=self.main_tab)
        self.main_stacked_widget.setGeometry(QtCore.QRect(0, 0, 711, 400))
        self.main_stacked_widget.setStyleSheet("QPushButt {\n"
"    border-image: url(:/simple_btn/MEDIA/test_media/btn_simple.png) 0 0 0 0 stretch stretch;\n"
"    color: #424242;\n"
"    min-height: 95px;\n"
"    max-height: 95px; \n"
"    min-width: 310px;\n"
"    max-width: 310px;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"\n"
"QPushButto::pressed {\n"
"    border-image: url(:/simple_btn/MEDIA/test_media/btn_simple_PRESSED.png) 0 0 0 0 stretch stretch;\n"
"    color: #8e8d8d;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"")
        self.main_stacked_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.Select_file_page = QtWidgets.QWidget()
        self.Select_file_page.setObjectName("Select_file_page")
        self.select_file_scroll_area = QtWidgets.QScrollArea(parent=self.Select_file_page)
        self.select_file_scroll_area.setGeometry(QtCore.QRect(60, 120, 481, 241))
        self.select_file_scroll_area.setWidgetResizable(True)
        self.select_file_scroll_area.setObjectName("select_file_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.select_file_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(parent=self.Select_file_page)
        self.pushButton.setGeometry(QtCore.QRect(580, 60, 71, 51))
        self.pushButton.setObjectName("pushButton")
        self.main_stacked_widget.addWidget(self.Select_file_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.main_page)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 661, 341))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_title = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.main_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.main_title.setStyleSheet("")
        self.main_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_title.setObjectName("main_title")
        self.verticalLayout.addWidget(self.main_title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.print_btn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.print_btn.setFont(font)
        self.print_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.print_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.print_btn.setObjectName("print_btn")
        self.verticalLayout.addWidget(self.print_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.main_text_box = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setItalic(False)
        self.main_text_box.setFont(font)
        self.main_text_box.setStyleSheet("#main_text_box{\n"
"    align-text: center;\n"
"    font-family: Montserrat;\n"
"    font-style: montserrat;\n"
"    font-size: 14pt;\n"
"    color: white;\n"
"    padding-left: 100px;\n"
"    padding-right: 100px;\n"
"}")
        self.main_text_box.setObjectName("main_text_box")
        self.verticalLayout.addWidget(self.main_text_box, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.main_stacked_widget.addWidget(self.main_page)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_home_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.mainTabWidget.addTab(self.main_tab, icon2, "")
        self.filament_tab = QtWidgets.QWidget()
        self.filament_tab.setObjectName("filament_tab")
        self.filament_stacked_widget = QtWidgets.QStackedWidget(parent=self.filament_tab)
        self.filament_stacked_widget.setGeometry(QtCore.QRect(0, 0, 710, 421))
        self.filament_stacked_widget.setStyleSheet("")
        self.filament_stacked_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.filament_stacked_widget.setObjectName("filament_stacked_widget")
        self.filament_page = QtWidgets.QWidget()
        self.filament_page.setObjectName("filament_page")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.filament_page)
        self.layoutWidget2.setGeometry(QtCore.QRect(9, 30, 691, 311))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.filament_grid = QtWidgets.QGridLayout(self.layoutWidget2)
        self.filament_grid.setContentsMargins(0, 0, 0, 0)
        self.filament_grid.setObjectName("filament_grid")
        self.filament_title = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.filament_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.filament_title.setStyleSheet("")
        self.filament_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filament_title.setObjectName("filament_title")
        self.filament_grid.addWidget(self.filament_title, 0, 0, 1, 1)
        self.filament_btns_grid = QtWidgets.QGridLayout()
        self.filament_btns_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.filament_btns_grid.setObjectName("filament_btns_grid")
        self.change_filament_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.change_filament_btn.setFont(font)
        self.change_filament_btn.setStyleSheet("#change_filament_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/change_filament.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#change_filament_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/change_filament_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.change_filament_btn.setObjectName("change_filament_btn")
        self.filament_btns_grid.addWidget(self.change_filament_btn, 2, 0, 1, 1)
        self.dryer_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.dryer_btn.setFont(font)
        self.dryer_btn.setStyleSheet("#dryer_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/dryer_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#dryer_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/dryer_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.dryer_btn.setObjectName("dryer_btn")
        self.filament_btns_grid.addWidget(self.dryer_btn, 2, 1, 1, 1)
        self.unload_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.unload_btn.setFont(font)
        self.unload_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.unload_btn.setObjectName("unload_btn")
        self.filament_btns_grid.addWidget(self.unload_btn, 0, 0, 1, 1)
        self.load_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.load_btn.setFont(font)
        self.load_btn.setStyleSheet("#load_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#load_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.load_btn.setObjectName("load_btn")
        self.filament_btns_grid.addWidget(self.load_btn, 0, 1, 1, 1)
        self.filament_grid.addLayout(self.filament_btns_grid, 1, 0, 1, 1)
        self.filament_stacked_widget.addWidget(self.filament_page)
        self.load_t1_page = QtWidgets.QWidget()
        self.load_t1_page.setObjectName("load_t1_page")
        self.load_t1_pla = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_pla.setGeometry(QtCore.QRect(50, 90, 310, 95))
        self.load_t1_pla.setObjectName("load_t1_pla")
        self.load_t1_petg = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_petg.setGeometry(QtCore.QRect(340, 90, 310, 95))
        self.load_t1_petg.setObjectName("load_t1_petg")
        self.load_t1_abs = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_abs.setGeometry(QtCore.QRect(50, 160, 310, 95))
        self.load_t1_abs.setObjectName("load_t1_abs")
        self.load_t1_hips = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_hips.setGeometry(QtCore.QRect(350, 160, 310, 95))
        self.load_t1_hips.setObjectName("load_t1_hips")
        self.load_t1_nylon = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_nylon.setGeometry(QtCore.QRect(50, 230, 310, 95))
        self.load_t1_nylon.setObjectName("load_t1_nylon")
        self.load_t1_tpu = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_tpu.setGeometry(QtCore.QRect(340, 230, 310, 95))
        self.load_t1_tpu.setObjectName("load_t1_tpu")
        self.load_t1_custom = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_custom.setGeometry(QtCore.QRect(190, 300, 310, 95))
        self.load_t1_custom.setObjectName("load_t1_custom")
        self.load_t1_title = QtWidgets.QLabel(parent=self.load_t1_page)
        self.load_t1_title.setGeometry(QtCore.QRect(210, 30, 271, 61))
        self.load_t1_title.setStyleSheet("")
        self.load_t1_title.setObjectName("load_t1_title")
        self.filament_stacked_widget.addWidget(self.load_t1_page)
        self.load_t2_page = QtWidgets.QWidget()
        self.load_t2_page.setObjectName("load_t2_page")
        self.load_t2_nylon = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_nylon.setGeometry(QtCore.QRect(50, 230, 310, 95))
        self.load_t2_nylon.setObjectName("load_t2_nylon")
        self.load_t2_abs = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_abs.setGeometry(QtCore.QRect(50, 160, 310, 95))
        self.load_t2_abs.setObjectName("load_t2_abs")
        self.load_t2_pla = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_pla.setGeometry(QtCore.QRect(50, 90, 310, 95))
        self.load_t2_pla.setObjectName("load_t2_pla")
        self.load_t2_title = QtWidgets.QLabel(parent=self.load_t2_page)
        self.load_t2_title.setGeometry(QtCore.QRect(210, 30, 271, 61))
        self.load_t2_title.setStyleSheet("")
        self.load_t2_title.setObjectName("load_t2_title")
        self.load_t2_tpu = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_tpu.setGeometry(QtCore.QRect(340, 230, 310, 95))
        self.load_t2_tpu.setObjectName("load_t2_tpu")
        self.load_t2_petg = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_petg.setGeometry(QtCore.QRect(340, 90, 310, 95))
        self.load_t2_petg.setObjectName("load_t2_petg")
        self.load_t2_custom = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_custom.setGeometry(QtCore.QRect(190, 300, 310, 95))
        self.load_t2_custom.setObjectName("load_t2_custom")
        self.load_t2_hips = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_hips.setGeometry(QtCore.QRect(350, 160, 310, 95))
        self.load_t2_hips.setObjectName("load_t2_hips")
        self.filament_stacked_widget.addWidget(self.load_t2_page)
        self.dryers_page = QtWidgets.QWidget()
        self.dryers_page.setObjectName("dryers_page")
        self.dryer_1_icon = QtWidgets.QLabel(parent=self.dryers_page)
        self.dryer_1_icon.setGeometry(QtCore.QRect(70, 110, 91, 61))
        self.dryer_1_icon.setObjectName("dryer_1_icon")
        self.dryer_2_icon = QtWidgets.QLabel(parent=self.dryers_page)
        self.dryer_2_icon.setGeometry(QtCore.QRect(440, 110, 91, 61))
        self.dryer_2_icon.setObjectName("dryer_2_icon")
        self.dryers_title = QtWidgets.QLabel(parent=self.dryers_page)
        self.dryers_title.setGeometry(QtCore.QRect(290, 40, 111, 61))
        self.dryers_title.setObjectName("dryers_title")
        self.dryer_1_auto_btn = QtWidgets.QPushButton(parent=self.dryers_page)
        self.dryer_1_auto_btn.setGeometry(QtCore.QRect(50, 210, 310, 95))
        self.dryer_1_auto_btn.setObjectName("dryer_1_auto_btn")
        self.dryer_1_off_btn = QtWidgets.QPushButton(parent=self.dryers_page)
        self.dryer_1_off_btn.setGeometry(QtCore.QRect(50, 300, 310, 95))
        self.dryer_1_off_btn.setObjectName("dryer_1_off_btn")
        self.dryer_2_auto_btn = QtWidgets.QPushButton(parent=self.dryers_page)
        self.dryer_2_auto_btn.setGeometry(QtCore.QRect(360, 210, 310, 95))
        self.dryer_2_auto_btn.setObjectName("dryer_2_auto_btn")
        self.dryer_2_off_btn = QtWidgets.QPushButton(parent=self.dryers_page)
        self.dryer_2_off_btn.setGeometry(QtCore.QRect(360, 300, 310, 95))
        self.dryer_2_off_btn.setObjectName("dryer_2_off_btn")
        self.filament_stacked_widget.addWidget(self.dryers_page)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_filament.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_filament_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.mainTabWidget.addTab(self.filament_tab, icon3, "")
        self.control_tab = QtWidgets.QWidget()
        self.control_tab.setObjectName("control_tab")
        self.control_stacked_widget = QtWidgets.QStackedWidget(parent=self.control_tab)
        self.control_stacked_widget.setGeometry(QtCore.QRect(0, 0, 711, 421))
        self.control_stacked_widget.setStyleSheet("")
        self.control_stacked_widget.setLineWidth(3)
        self.control_stacked_widget.setObjectName("control_stacked_widget")
        self.control_page = QtWidgets.QWidget()
        self.control_page.setObjectName("control_page")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.control_page)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 42, 634, 353))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.control_grid = QtWidgets.QGridLayout(self.layoutWidget3)
        self.control_grid.setContentsMargins(0, 0, 0, 0)
        self.control_grid.setObjectName("control_grid")
        self.control_btns_grid = QtWidgets.QGridLayout()
        self.control_btns_grid.setObjectName("control_btns_grid")
        self.printer_settings_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.printer_settings_btn.setObjectName("printer_settings_btn")
        self.control_btns_grid.addWidget(self.printer_settings_btn, 2, 0, 1, 1)
        self.bed_leveling_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.bed_leveling_btn.setObjectName("bed_leveling_btn")
        self.control_btns_grid.addWidget(self.bed_leveling_btn, 1, 0, 1, 1)
        self.switch_print_core_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.switch_print_core_btn.setObjectName("switch_print_core_btn")
        self.control_btns_grid.addWidget(self.switch_print_core_btn, 2, 1, 1, 1)
        self.motion_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.motion_btn.setObjectName("motion_btn")
        self.control_btns_grid.addWidget(self.motion_btn, 0, 1, 1, 1)
        self.temperature_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.temperature_btn.setObjectName("temperature_btn")
        self.control_btns_grid.addWidget(self.temperature_btn, 0, 0, 1, 1)
        self.nozzles_calibration_btn = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.nozzles_calibration_btn.setObjectName("nozzles_calibration_btn")
        self.control_btns_grid.addWidget(self.nozzles_calibration_btn, 1, 1, 1, 1)
        self.control_grid.addLayout(self.control_btns_grid, 1, 0, 1, 1)
        self.control_title = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.control_title.setStyleSheet("")
        self.control_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.control_title.setObjectName("control_title")
        self.control_grid.addWidget(self.control_title, 0, 0, 1, 1)
        self.control_stacked_widget.addWidget(self.control_page)
        self.motion_page = QtWidgets.QWidget()
        self.motion_page.setObjectName("motion_page")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.motion_page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 691, 311))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.motion_grid = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.motion_grid.setContentsMargins(0, 0, 0, 0)
        self.motion_grid.setObjectName("motion_grid")
        self.motion_title = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.motion_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.motion_title.setStyleSheet("")
        self.motion_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motion_title.setObjectName("motion_title")
        self.motion_grid.addWidget(self.motion_title, 0, 0, 1, 1)
        self.motion_btns_grid = QtWidgets.QGridLayout()
        self.motion_btns_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.motion_btns_grid.setObjectName("motion_btns_grid")
        self.auto_home_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.auto_home_btn.setFont(font)
        self.auto_home_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.auto_home_btn.setObjectName("auto_home_btn")
        self.motion_btns_grid.addWidget(self.auto_home_btn, 1, 1, 1, 1)
        self.disable_steppers_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.disable_steppers_btn.setFont(font)
        self.disable_steppers_btn.setStyleSheet("#load_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#load_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/filament_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.disable_steppers_btn.setObjectName("disable_steppers_btn")
        self.motion_btns_grid.addWidget(self.disable_steppers_btn, 1, 0, 1, 1)
        self.extrude_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.extrude_btn.setFont(font)
        self.extrude_btn.setStyleSheet("#change_filament_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/change_filament.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#change_filament_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/change_filament_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.extrude_btn.setObjectName("extrude_btn")
        self.motion_btns_grid.addWidget(self.extrude_btn, 2, 0, 1, 1)
        self.move_axis_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(20)
        font.setItalic(False)
        self.move_axis_btn.setFont(font)
        self.move_axis_btn.setStyleSheet("#dryer_btn {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/dryer_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#dryer_btn::pressed {\n"
"    image:url(:/General_icons/MEDIA/test_media/icons/dryer_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.move_axis_btn.setObjectName("move_axis_btn")
        self.motion_btns_grid.addWidget(self.move_axis_btn, 2, 1, 1, 1)
        self.motion_grid.addLayout(self.motion_btns_grid, 1, 0, 1, 1)
        self.control_stacked_widget.addWidget(self.motion_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.control_stacked_widget.addWidget(self.page)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_control.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_control_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.mainTabWidget.addTab(self.control_tab, icon4, "")
        self.utilities_tab = QtWidgets.QWidget()
        self.utilities_tab.setObjectName("utilities_tab")
        self.utilities_stacked_widget = QtWidgets.QStackedWidget(parent=self.utilities_tab)
        self.utilities_stacked_widget.setGeometry(QtCore.QRect(0, 0, 711, 400))
        self.utilities_stacked_widget.setStyleSheet("QStackedWidget {\n"
"    background-colour: black;\n"
"}")
        self.utilities_stacked_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.utilities_stacked_widget.setObjectName("utilities_stacked_widget")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page_9)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 80, 310, 95))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page_9)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 190, 310, 95))
        self.pushButton_3.setObjectName("pushButton_3")
        self.utilities_stacked_widget.addWidget(self.page_9)
        self.utilities_page = QtWidgets.QWidget()
        self.utilities_page.setObjectName("utilities_page")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.utilities_page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 16, 684, 371))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.utilities_grid = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.utilities_grid.setContentsMargins(0, 0, 0, 0)
        self.utilities_grid.setVerticalSpacing(0)
        self.utilities_grid.setObjectName("utilities_grid")
        self.utilities_btns_grid = QtWidgets.QGridLayout()
        self.utilities_btns_grid.setContentsMargins(-1, 0, -1, -1)
        self.utilities_btns_grid.setSpacing(0)
        self.utilities_btns_grid.setObjectName("utilities_btns_grid")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.utilities_btns_grid.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.utilities_btns_grid.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.utilities_btns_grid.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.utilities_btns_grid.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.utilities_btns_grid.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.utilities_btns_grid.addWidget(self.pushButton_15, 1, 1, 1, 1)
        self.utilities_grid.addLayout(self.utilities_btns_grid, 1, 0, 1, 1)
        self.utilities_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.utilities_title.setStyleSheet("")
        self.utilities_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.utilities_title.setObjectName("utilities_title")
        self.utilities_grid.addWidget(self.utilities_title, 0, 0, 1, 1)
        self.utilities_stacked_widget.addWidget(self.utilities_page)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_utilities.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/General_icons/MEDIA/1_icons/main_menu/ICON_utilities_pressed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.mainTabWidget.addTab(self.utilities_tab, icon5, "")
        self.central_grid.addWidget(self.mainTabWidget, 1, 0, 1, 1)
        self.central_grid.setRowStretch(0, 4)
        self.central_grid.setRowStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(3)
        self.main_stacked_widget.setCurrentIndex(1)
        self.filament_stacked_widget.setCurrentIndex(0)
        self.control_stacked_widget.setCurrentIndex(0)
        self.utilities_stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chamber_temp.setText(_translate("MainWindow", "30 ºC /60 ºC"))
        self.filament_type_1.setText(_translate("MainWindow", "PLA"))
        self.hot_bed_temp.setText(_translate("MainWindow", "45 ºC /50 ºC"))
        self.filament_type_2.setText(_translate("MainWindow", "PLA"))
        self.nozzle_1_temp.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.nozzle_2_temp.setText(_translate("MainWindow", "210 ºC /220 ºC"))
        self.nozzle_1.setText(_translate("MainWindow", "Nozzle: 0.4"))
        self.nozzle_2.setText(_translate("MainWindow", "Nozzle: 0.3"))
        self.wifi_signal.setText(_translate("MainWindow", "Wifi"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton.setProperty("class", _translate("MainWindow", "back_btn"))
        self.main_title.setText(_translate("MainWindow", "Filament"))
        self.main_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.print_btn.setText(_translate("MainWindow", "PRINT"))
        self.print_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.main_text_box.setText(_translate("MainWindow", "Printer ready to use"))
        self.filament_title.setText(_translate("MainWindow", "Filament"))
        self.filament_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.change_filament_btn.setText(_translate("MainWindow", "change\n"
"filament"))
        self.change_filament_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.dryer_btn.setText(_translate("MainWindow", "dryer"))
        self.dryer_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.unload_btn.setText(_translate("MainWindow", "unload"))
        self.unload_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_btn.setText(_translate("MainWindow", "load"))
        self.load_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_pla.setText(_translate("MainWindow", "PLA"))
        self.load_t1_pla.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_petg.setText(_translate("MainWindow", "PETG"))
        self.load_t1_petg.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_abs.setText(_translate("MainWindow", "ABS"))
        self.load_t1_abs.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_hips.setText(_translate("MainWindow", "HIPS"))
        self.load_t1_hips.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_nylon.setText(_translate("MainWindow", "NYLON"))
        self.load_t1_nylon.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_tpu.setText(_translate("MainWindow", "TPU"))
        self.load_t1_tpu.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_custom.setText(_translate("MainWindow", "CUSTOM"))
        self.load_t1_custom.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t1_title.setText(_translate("MainWindow", "Load Tool Head 1 "))
        self.load_t1_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.load_t2_nylon.setText(_translate("MainWindow", "NYLON"))
        self.load_t2_nylon.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_abs.setText(_translate("MainWindow", "ABS"))
        self.load_t2_abs.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_pla.setText(_translate("MainWindow", "PLA"))
        self.load_t2_pla.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_title.setText(_translate("MainWindow", "Load Tool Head 2"))
        self.load_t2_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.load_t2_tpu.setText(_translate("MainWindow", "TPU"))
        self.load_t2_tpu.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_petg.setText(_translate("MainWindow", "PETG"))
        self.load_t2_petg.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_custom.setText(_translate("MainWindow", "CUSTOM"))
        self.load_t2_custom.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.load_t2_hips.setText(_translate("MainWindow", "HIPS"))
        self.load_t2_hips.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.dryer_1_icon.setText(_translate("MainWindow", "Dryer Icon"))
        self.dryer_2_icon.setText(_translate("MainWindow", "Dryer 2 Icon"))
        self.dryers_title.setText(_translate("MainWindow", "Dryers"))
        self.dryers_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.dryer_1_auto_btn.setText(_translate("MainWindow", "auto temperature"))
        self.dryer_1_auto_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.dryer_1_off_btn.setText(_translate("MainWindow", "turn off dryer"))
        self.dryer_1_off_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.dryer_2_auto_btn.setText(_translate("MainWindow", "Auto temperature"))
        self.dryer_2_auto_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.dryer_2_off_btn.setText(_translate("MainWindow", "turn off dryer"))
        self.dryer_2_off_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.printer_settings_btn.setText(_translate("MainWindow", "Printer\n"
"Settings"))
        self.printer_settings_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.bed_leveling_btn.setText(_translate("MainWindow", "Bed\n"
"Leveling"))
        self.bed_leveling_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.switch_print_core_btn.setText(_translate("MainWindow", "Switch\n"
"Print Core"))
        self.switch_print_core_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.motion_btn.setText(_translate("MainWindow", "Motion"))
        self.motion_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.temperature_btn.setText(_translate("MainWindow", "Temperature"))
        self.temperature_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.nozzles_calibration_btn.setText(_translate("MainWindow", "nozzles\n"
"calibration"))
        self.nozzles_calibration_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.control_title.setText(_translate("MainWindow", "Control"))
        self.control_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.motion_title.setText(_translate("MainWindow", "Motion"))
        self.motion_title.setProperty("class", _translate("MainWindow", "title_text"))
        self.auto_home_btn.setText(_translate("MainWindow", "auto home"))
        self.auto_home_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.disable_steppers_btn.setText(_translate("MainWindow", "disable\n"
"steppers"))
        self.disable_steppers_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.extrude_btn.setText(_translate("MainWindow", "extrude"))
        self.extrude_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.move_axis_btn.setText(_translate("MainWindow", "move axis"))
        self.move_axis_btn.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_2.setText(_translate("MainWindow", "LEDs"))
        self.pushButton_2.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_10.setText(_translate("MainWindow", "Axes\n"
"Maintenance"))
        self.pushButton_10.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_11.setText(_translate("MainWindow", "Routine\n"
"Check"))
        self.pushButton_11.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_12.setText(_translate("MainWindow", "Factory Reset"))
        self.pushButton_12.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_13.setText(_translate("MainWindow", "LEDs"))
        self.pushButton_13.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_14.setText(_translate("MainWindow", "Info"))
        self.pushButton_14.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.pushButton_15.setText(_translate("MainWindow", "LCD Settings"))
        self.pushButton_15.setProperty("class", _translate("MainWindow", "menu_btn"))
        self.utilities_title.setText(_translate("MainWindow", "Utilities"))
        self.utilities_title.setProperty("class", _translate("MainWindow", "title_text"))
