# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/Qt_UI/connectionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setAutoFillBackground(False)
        self.ButtonFrame = QtWidgets.QFrame(parent=Form)
        self.ButtonFrame.setGeometry(QtCore.QRect(-1, 426, 800, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonFrame.sizePolicy().hasHeightForWidth())
        self.ButtonFrame.setSizePolicy(sizePolicy)
        self.ButtonFrame.setMinimumSize(QtCore.QSize(800, 50))
        self.ButtonFrame.setBaseSize(QtCore.QSize(0, 0))
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ButtonFrame.setLineWidth(1)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.ButtonLayout_1 = QtWidgets.QHBoxLayout(self.ButtonFrame)
        self.ButtonLayout_1.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ButtonLayout_1.setContentsMargins(0, 0, 0, 0)
        self.ButtonLayout_1.setSpacing(0)
        self.ButtonLayout_1.setObjectName("ButtonLayout_1")
        self.RetryConnection = QtWidgets.QPushButton(parent=self.ButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RetryConnection.sizePolicy().hasHeightForWidth())
        self.RetryConnection.setSizePolicy(sizePolicy)
        self.RetryConnection.setMinimumSize(QtCore.QSize(400, 50))
        self.RetryConnection.setObjectName("RetryConnection")
        self.ButtonLayout_1.addWidget(self.RetryConnection)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.ButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_2.setBaseSize(QtCore.QSize(0, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.ButtonLayout_1.addWidget(self.pushButton_2)
        self.TextFrame = QtWidgets.QFrame(parent=Form)
        self.TextFrame.setGeometry(QtCore.QRect(0, 0, 800, 430))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextFrame.sizePolicy().hasHeightForWidth())
        self.TextFrame.setSizePolicy(sizePolicy)
        self.TextFrame.setMinimumSize(QtCore.QSize(800, 430))
        self.TextFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TextFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TextFrame.setObjectName("TextFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.TextFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.connectionTextBox = QtWidgets.QTextEdit(parent=Form)
        self.connectionTextBox.setGeometry(QtCore.QRect(270, 120, 256, 192))
        self.connectionTextBox.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDialableCharactersOnly|QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly|QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly|QtCore.Qt.InputMethodHint.ImhLatinOnly|QtCore.Qt.InputMethodHint.ImhLowercaseOnly|QtCore.Qt.InputMethodHint.ImhNoEditMenu|QtCore.Qt.InputMethodHint.ImhUppercaseOnly|QtCore.Qt.InputMethodHint.ImhUrlCharactersOnly)
        self.connectionTextBox.setObjectName("connectionTextBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RetryConnection.setText(_translate("Form", "RetryKlipperCon"))
        self.pushButton_2.setText(_translate("Form", "RetryWebsocketCon"))
