# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/qt_ui/connectionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectivityForm(object):
    def setupUi(self, ConnectivityForm):
        ConnectivityForm.setObjectName("ConnectivityForm")
        ConnectivityForm.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConnectivityForm.sizePolicy().hasHeightForWidth())
        ConnectivityForm.setSizePolicy(sizePolicy)
        ConnectivityForm.setMinimumSize(QtCore.QSize(800, 480))
        ConnectivityForm.setMaximumSize(QtCore.QSize(800, 480))
        ConnectivityForm.setWindowOpacity(1.0)
        ConnectivityForm.setAutoFillBackground(False)
        ConnectivityForm.setStyleSheet("#ConnectivityForm{\n"
"    background-image: url(:/Main_background/1st_background.png);\n"
"}\n"
"#ButtonFrame > QPushButton{\n"
"    border-image: url(:/Svgtype/media/btn_small.svg);\n"
"    color: #424242;\n"
"    min-height: 80px;\n"
"    max-height: 80px; \n"
"    min-width: 200px;\n"
"    max-width: 200px;    \n"
"}\n"
"#ButtonFrame > QPushButton::pressed{\n"
"    border-image: url(:/Svgtype/media/btn_small_PRESSED.svg);\n"
"    color: #8e8d8d;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"#ButtonFrame > CustomQPushButton::pressed{\n"
"    border-image: url(:/Svgtype/media/btn_small_PRESSED.svg);\n"
"    color: #8e8d8d;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"}\n"
"#TextFrame > QLabel{\n"
"    text-align: center;\n"
"    font-family: Momcake;\n"
"    font-style: normal;\n"
"    font-size: 18pt;\n"
"    color: rgba(255,255,255,1);\n"
"    text-align: center\n"
"}")
        ConnectivityForm.setProperty("class", "")
        self.ButtonFrame = QtWidgets.QFrame(parent=ConnectivityForm)
        self.ButtonFrame.setGeometry(QtCore.QRect(-1, 400, 800, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonFrame.sizePolicy().hasHeightForWidth())
        self.ButtonFrame.setSizePolicy(sizePolicy)
        self.ButtonFrame.setMinimumSize(QtCore.QSize(800, 80))
        self.ButtonFrame.setMaximumSize(QtCore.QSize(800, 80))
        self.ButtonFrame.setBaseSize(QtCore.QSize(800, 100))
        self.ButtonFrame.setStyleSheet("")
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.ButtonFrame.setLineWidth(0)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.RestartKlipperButton = CustomQPushButton(parent=self.ButtonFrame)
        self.RestartKlipperButton.setGeometry(QtCore.QRect(0, 0, 200, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RestartKlipperButton.sizePolicy().hasHeightForWidth())
        self.RestartKlipperButton.setSizePolicy(sizePolicy)
        self.RestartKlipperButton.setMinimumSize(QtCore.QSize(200, 80))
        self.RestartKlipperButton.setBaseSize(QtCore.QSize(200, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        self.RestartKlipperButton.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.RestartKlipperButton.setFont(font)
        self.RestartKlipperButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.RestartKlipperButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.RestartKlipperButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.RestartKlipperButton.setAutoFillBackground(False)
        self.RestartKlipperButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Svgtype/media/icons/restart_klippersvg.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/Svgtype/media/icons/restart_klippersvg_PRESSED.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.RestartKlipperButton.setIcon(icon)
        self.RestartKlipperButton.setIconSize(QtCore.QSize(46, 42))
        self.RestartKlipperButton.setCheckable(False)
        self.RestartKlipperButton.setAutoRepeat(False)
        self.RestartKlipperButton.setAutoExclusive(False)
        self.RestartKlipperButton.setAutoRepeatDelay(0)
        self.RestartKlipperButton.setAutoRepeatInterval(0)
        self.RestartKlipperButton.setProperty("setIconPosition", QtCore.QPoint(-2, -2))
        self.RestartKlipperButton.setObjectName("RestartKlipperButton")
        self.RetryConnectionButton = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.RetryConnectionButton.setGeometry(QtCore.QRect(204, 0, 200, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RetryConnectionButton.sizePolicy().hasHeightForWidth())
        self.RetryConnectionButton.setSizePolicy(sizePolicy)
        self.RetryConnectionButton.setMinimumSize(QtCore.QSize(200, 80))
        self.RetryConnectionButton.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.RetryConnectionButton.setAutoFillBackground(False)
        self.RetryConnectionButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/retry_connection.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/retry_connection_PRESSED.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.RetryConnectionButton.setIcon(icon1)
        self.RetryConnectionButton.setAutoDefault(False)
        self.RetryConnectionButton.setDefault(False)
        self.RetryConnectionButton.setFlat(False)
        self.RetryConnectionButton.setObjectName("RetryConnectionButton")
        self.WifiButton = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.WifiButton.setGeometry(QtCore.QRect(403, 0, 200, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WifiButton.sizePolicy().hasHeightForWidth())
        self.WifiButton.setSizePolicy(sizePolicy)
        self.WifiButton.setMinimumSize(QtCore.QSize(200, 80))
        self.WifiButton.setMaximumSize(QtCore.QSize(200, 80))
        self.WifiButton.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.WifiButton.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/wifi_settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/wifi_settings_PRESSED.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.WifiButton.setIcon(icon2)
        self.WifiButton.setAutoDefault(False)
        self.WifiButton.setDefault(False)
        self.WifiButton.setFlat(False)
        self.WifiButton.setObjectName("WifiButton")
        self.pushButton = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.pushButton.setGeometry(QtCore.QRect(601, 0, 200, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 80))
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.pushButton.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/system_reboot.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/General_icons/media/icons/system_reboot_PRESSED.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton.setIcon(icon3)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.RetryConnectionButton.raise_()
        self.WifiButton.raise_()
        self.pushButton.raise_()
        self.RestartKlipperButton.raise_()
        self.TextFrame = QtWidgets.QFrame(parent=ConnectivityForm)
        self.TextFrame.setGeometry(QtCore.QRect(0, 0, 800, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextFrame.sizePolicy().hasHeightForWidth())
        self.TextFrame.setSizePolicy(sizePolicy)
        self.TextFrame.setMinimumSize(QtCore.QSize(800, 400))
        self.TextFrame.setMaximumSize(QtCore.QSize(800, 400))
        palette = QtGui.QPalette()
        self.TextFrame.setPalette(palette)
        self.TextFrame.setAutoFillBackground(False)
        self.TextFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.TextFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TextFrame.setObjectName("TextFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TextFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connectionTextBox = QtWidgets.QLabel(parent=self.TextFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionTextBox.sizePolicy().hasHeightForWidth())
        self.connectionTextBox.setSizePolicy(sizePolicy)
        self.connectionTextBox.setMaximumSize(QtCore.QSize(800, 400))
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(18)
        font.setItalic(False)
        self.connectionTextBox.setFont(font)
        self.connectionTextBox.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.connectionTextBox.setScaledContents(False)
        self.connectionTextBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.connectionTextBox.setWordWrap(False)
        self.connectionTextBox.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.connectionTextBox.setObjectName("connectionTextBox")
        self.verticalLayout.addWidget(self.connectionTextBox)

        self.retranslateUi(ConnectivityForm)
        QtCore.QMetaObject.connectSlotsByName(ConnectivityForm)

    def retranslateUi(self, ConnectivityForm):
        _translate = QtCore.QCoreApplication.translate
        ConnectivityForm.setWindowTitle(_translate("ConnectivityForm", "Form"))
        self.RestartKlipperButton.setText(_translate("ConnectivityForm", "Restart Klipper"))
        self.RetryConnectionButton.setText(_translate("ConnectivityForm", "Retry Connection"))
        self.RetryConnectionButton.setProperty("class", _translate("ConnectivityForm", "system_control_btn"))
        self.WifiButton.setText(_translate("ConnectivityForm", "Wifi Settings"))
        self.WifiButton.setProperty("class", _translate("ConnectivityForm", "system_control_btn"))
        self.pushButton.setText(_translate("ConnectivityForm", "Reboot System"))
        self.pushButton.setProperty("class", _translate("ConnectivityForm", "system_control_btn"))
        self.connectionTextBox.setText(_translate("ConnectivityForm", "TextLabel"))
from qt_ui.ui_util import CustomQPushButton
