# Form implementation generated from reading ui file '/home/gleb/github/Blocks_Screen/qt_ui/controlStackedWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_controlStackedWidget(object):
    def setupUi(self, controlStackedWidget):
        controlStackedWidget.setObjectName("controlStackedWidget")
        controlStackedWidget.resize(400, 300)
        self.control_page = QtWidgets.QWidget()
        self.control_page.setObjectName("control_page")
        self.layoutWidget = QtWidgets.QWidget(parent=self.control_page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 634, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.control_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.control_grid.setContentsMargins(0, 0, 0, 0)
        self.control_grid.setObjectName("control_grid")
        self.control_btns_grid = QtWidgets.QGridLayout()
        self.control_btns_grid.setObjectName("control_btns_grid")
        self.printer_settings_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.printer_settings_btn.setObjectName("printer_settings_btn")
        self.control_btns_grid.addWidget(self.printer_settings_btn, 2, 0, 1, 1)
        self.bed_leveling_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.bed_leveling_btn.setObjectName("bed_leveling_btn")
        self.control_btns_grid.addWidget(self.bed_leveling_btn, 1, 0, 1, 1)
        self.switch_print_core_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.switch_print_core_btn.setObjectName("switch_print_core_btn")
        self.control_btns_grid.addWidget(self.switch_print_core_btn, 2, 1, 1, 1)
        self.motion_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.motion_btn.setObjectName("motion_btn")
        self.control_btns_grid.addWidget(self.motion_btn, 0, 1, 1, 1)
        self.temperature_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.temperature_btn.setObjectName("temperature_btn")
        self.control_btns_grid.addWidget(self.temperature_btn, 0, 0, 1, 1)
        self.nozzles_calibration_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.nozzles_calibration_btn.setObjectName("nozzles_calibration_btn")
        self.control_btns_grid.addWidget(self.nozzles_calibration_btn, 1, 1, 1, 1)
        self.control_grid.addLayout(self.control_btns_grid, 1, 0, 1, 1)
        self.control_title = QtWidgets.QLabel(parent=self.layoutWidget)
        self.control_title.setStyleSheet("")
        self.control_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.control_title.setObjectName("control_title")
        self.control_grid.addWidget(self.control_title, 0, 0, 1, 1)
        controlStackedWidget.addWidget(self.control_page)
        self.motion_page = QtWidgets.QWidget()
        self.motion_page.setObjectName("motion_page")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.motion_page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 691, 311))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.motion_grid = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.motion_grid.setContentsMargins(0, 0, 0, 0)
        self.motion_grid.setObjectName("motion_grid")
        self.motion_title = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.motion_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.motion_title.setStyleSheet("")
        self.motion_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motion_title.setObjectName("motion_title")
        self.motion_grid.addWidget(self.motion_title, 0, 0, 1, 1)
        self.motion_btns_grid = QtWidgets.QGridLayout()
        self.motion_btns_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.motion_btns_grid.setObjectName("motion_btns_grid")
        self.auto_home_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.auto_home_btn.setFont(font)
        self.auto_home_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.auto_home_btn.setObjectName("auto_home_btn")
        self.motion_btns_grid.addWidget(self.auto_home_btn, 1, 1, 1, 1)
        self.disable_steppers_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.disable_steppers_btn.setFont(font)
        self.disable_steppers_btn.setStyleSheet("#load_btn {\n"
"    image:url(:/General_icons/test_media/icons/filament_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#load_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/filament_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.disable_steppers_btn.setObjectName("disable_steppers_btn")
        self.motion_btns_grid.addWidget(self.disable_steppers_btn, 1, 0, 1, 1)
        self.extrude_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.extrude_btn.setFont(font)
        self.extrude_btn.setStyleSheet("#change_filament_btn {\n"
"    image:url(:/General_icons/test_media/icons/change_filament.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#change_filament_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/change_filament_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.extrude_btn.setObjectName("extrude_btn")
        self.motion_btns_grid.addWidget(self.extrude_btn, 2, 0, 1, 1)
        self.move_axis_btn = QtWidgets.QPushButton(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.move_axis_btn.setFont(font)
        self.move_axis_btn.setStyleSheet("#dryer_btn {\n"
"    image:url(:/General_icons/test_media/icons/dryer_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#dryer_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/dryer_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.move_axis_btn.setObjectName("move_axis_btn")
        self.motion_btns_grid.addWidget(self.move_axis_btn, 2, 1, 1, 1)
        self.motion_grid.addLayout(self.motion_btns_grid, 1, 0, 1, 1)
        controlStackedWidget.addWidget(self.motion_page)

        self.retranslateUi(controlStackedWidget)
        QtCore.QMetaObject.connectSlotsByName(controlStackedWidget)

    def retranslateUi(self, controlStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        controlStackedWidget.setWindowTitle(_translate("controlStackedWidget", "StackedWidget"))
        self.printer_settings_btn.setText(_translate("controlStackedWidget", "Printer\n"
"Settings"))
        self.printer_settings_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.bed_leveling_btn.setText(_translate("controlStackedWidget", "Bed\n"
"Leveling"))
        self.bed_leveling_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.switch_print_core_btn.setText(_translate("controlStackedWidget", "Switch\n"
"Print Core"))
        self.switch_print_core_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.motion_btn.setText(_translate("controlStackedWidget", "Motion"))
        self.motion_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.temperature_btn.setText(_translate("controlStackedWidget", "Temperature"))
        self.temperature_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.nozzles_calibration_btn.setText(_translate("controlStackedWidget", "nozzles\n"
"calibration"))
        self.nozzles_calibration_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.control_title.setText(_translate("controlStackedWidget", "Control"))
        self.control_title.setProperty("class", _translate("controlStackedWidget", "title_text"))
        self.motion_title.setText(_translate("controlStackedWidget", "Motion"))
        self.motion_title.setProperty("class", _translate("controlStackedWidget", "title_text"))
        self.auto_home_btn.setText(_translate("controlStackedWidget", "auto home"))
        self.auto_home_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.disable_steppers_btn.setText(_translate("controlStackedWidget", "disable\n"
"steppers"))
        self.disable_steppers_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.extrude_btn.setText(_translate("controlStackedWidget", "extrude"))
        self.extrude_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
        self.move_axis_btn.setText(_translate("controlStackedWidget", "move axis"))
        self.move_axis_btn.setProperty("class", _translate("controlStackedWidget", "menu_btn"))
