# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/qt_ui/filamentStackedWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_filamentStacketWidget(object):
    def setupUi(self, filamentStacketWidget):
        filamentStacketWidget.setObjectName("filamentStacketWidget")
        filamentStacketWidget.resize(821, 461)
        self.filament_page = QtWidgets.QWidget()
        self.filament_page.setObjectName("filament_page")
        self.layoutWidget = QtWidgets.QWidget(parent=self.filament_page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.filament_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.filament_grid.setContentsMargins(0, 0, 0, 0)
        self.filament_grid.setObjectName("filament_grid")
        self.filament_title = QtWidgets.QLabel(parent=self.layoutWidget)
        self.filament_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.filament_title.setStyleSheet("")
        self.filament_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filament_title.setObjectName("filament_title")
        self.filament_grid.addWidget(self.filament_title, 0, 0, 1, 1)
        self.filament_btns_grid = QtWidgets.QGridLayout()
        self.filament_btns_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.filament_btns_grid.setObjectName("filament_btns_grid")
        self.change_filament_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.change_filament_btn.setFont(font)
        self.change_filament_btn.setStyleSheet("#change_filament_btn {\n"
"    image:url(:/General_icons/test_media/icons/change_filament.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#change_filament_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/change_filament_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.change_filament_btn.setObjectName("change_filament_btn")
        self.filament_btns_grid.addWidget(self.change_filament_btn, 2, 0, 1, 1)
        self.dryer_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.dryer_btn.setFont(font)
        self.dryer_btn.setStyleSheet("#dryer_btn {\n"
"    image:url(:/General_icons/test_media/icons/dryer_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#dryer_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/dryer_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.dryer_btn.setObjectName("dryer_btn")
        self.filament_btns_grid.addWidget(self.dryer_btn, 2, 1, 1, 1)
        self.unload_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.unload_btn.setFont(font)
        self.unload_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.unload_btn.setObjectName("unload_btn")
        self.filament_btns_grid.addWidget(self.unload_btn, 0, 0, 1, 1)
        self.load_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        self.load_btn.setFont(font)
        self.load_btn.setStyleSheet("#load_btn {\n"
"    image:url(:/General_icons/test_media/icons/filament_icon.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#load_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/filament_icon_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.load_btn.setObjectName("load_btn")
        self.filament_btns_grid.addWidget(self.load_btn, 0, 1, 1, 1)
        self.filament_grid.addLayout(self.filament_btns_grid, 1, 0, 1, 1)
        filamentStacketWidget.addWidget(self.filament_page)
        self.load_t1_page = QtWidgets.QWidget()
        self.load_t1_page.setObjectName("load_t1_page")
        self.load_t1_pla = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_pla.setGeometry(QtCore.QRect(0, 60, 312, 97))
        self.load_t1_pla.setObjectName("load_t1_pla")
        self.load_t1_petg = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_petg.setGeometry(QtCore.QRect(290, 60, 312, 97))
        self.load_t1_petg.setObjectName("load_t1_petg")
        self.load_t1_tpu = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_tpu.setGeometry(QtCore.QRect(290, 200, 312, 97))
        self.load_t1_tpu.setObjectName("load_t1_tpu")
        self.load_t1_custom = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_custom.setGeometry(QtCore.QRect(140, 270, 312, 97))
        self.load_t1_custom.setObjectName("load_t1_custom")
        self.load_t1_nylon = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_nylon.setGeometry(QtCore.QRect(0, 200, 312, 97))
        self.load_t1_nylon.setObjectName("load_t1_nylon")
        self.load_t1_hips = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_hips.setGeometry(QtCore.QRect(300, 130, 312, 97))
        self.load_t1_hips.setObjectName("load_t1_hips")
        self.load_t1_abs = QtWidgets.QPushButton(parent=self.load_t1_page)
        self.load_t1_abs.setGeometry(QtCore.QRect(0, 130, 312, 97))
        self.load_t1_abs.setObjectName("load_t1_abs")
        self.load_t1_title = QtWidgets.QLabel(parent=self.load_t1_page)
        self.load_t1_title.setGeometry(QtCore.QRect(160, 0, 271, 61))
        self.load_t1_title.setStyleSheet("")
        self.load_t1_title.setObjectName("load_t1_title")
        filamentStacketWidget.addWidget(self.load_t1_page)
        self.load_t2_page = QtWidgets.QWidget()
        self.load_t2_page.setObjectName("load_t2_page")
        self.load_t2_pla = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_pla.setGeometry(QtCore.QRect(0, 60, 312, 97))
        self.load_t2_pla.setObjectName("load_t2_pla")
        self.load_t2_petg = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_petg.setGeometry(QtCore.QRect(290, 60, 312, 97))
        self.load_t2_petg.setObjectName("load_t2_petg")
        self.load_t2_abs = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_abs.setGeometry(QtCore.QRect(0, 130, 312, 97))
        self.load_t2_abs.setObjectName("load_t2_abs")
        self.load_t2_custom = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_custom.setGeometry(QtCore.QRect(140, 270, 312, 97))
        self.load_t2_custom.setObjectName("load_t2_custom")
        self.load_t2_nylon = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_nylon.setGeometry(QtCore.QRect(0, 200, 312, 97))
        self.load_t2_nylon.setObjectName("load_t2_nylon")
        self.load_t2_hips = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_hips.setGeometry(QtCore.QRect(300, 130, 312, 97))
        self.load_t2_hips.setObjectName("load_t2_hips")
        self.load_t2_title = QtWidgets.QLabel(parent=self.load_t2_page)
        self.load_t2_title.setGeometry(QtCore.QRect(160, 0, 271, 61))
        self.load_t2_title.setStyleSheet("")
        self.load_t2_title.setObjectName("load_t2_title")
        self.load_t2_tpu = QtWidgets.QPushButton(parent=self.load_t2_page)
        self.load_t2_tpu.setGeometry(QtCore.QRect(290, 200, 312, 97))
        self.load_t2_tpu.setObjectName("load_t2_tpu")
        filamentStacketWidget.addWidget(self.load_t2_page)
        self.dryer_page = QtWidgets.QWidget()
        self.dryer_page.setObjectName("dryer_page")
        self.dryer_1_icon = QtWidgets.QLabel(parent=self.dryer_page)
        self.dryer_1_icon.setGeometry(QtCore.QRect(20, 70, 91, 61))
        self.dryer_1_icon.setObjectName("dryer_1_icon")
        self.dryer_2_auto_btn = QtWidgets.QPushButton(parent=self.dryer_page)
        self.dryer_2_auto_btn.setGeometry(QtCore.QRect(310, 170, 312, 97))
        self.dryer_2_auto_btn.setObjectName("dryer_2_auto_btn")
        self.dryer_2_icon = QtWidgets.QLabel(parent=self.dryer_page)
        self.dryer_2_icon.setGeometry(QtCore.QRect(390, 70, 91, 61))
        self.dryer_2_icon.setObjectName("dryer_2_icon")
        self.dryer_1_auto_btn = QtWidgets.QPushButton(parent=self.dryer_page)
        self.dryer_1_auto_btn.setGeometry(QtCore.QRect(0, 170, 312, 97))
        self.dryer_1_auto_btn.setObjectName("dryer_1_auto_btn")
        self.dryers_title = QtWidgets.QLabel(parent=self.dryer_page)
        self.dryers_title.setGeometry(QtCore.QRect(240, 0, 111, 61))
        self.dryers_title.setObjectName("dryers_title")
        self.dryer_2_off_btn = QtWidgets.QPushButton(parent=self.dryer_page)
        self.dryer_2_off_btn.setGeometry(QtCore.QRect(310, 260, 312, 97))
        self.dryer_2_off_btn.setObjectName("dryer_2_off_btn")
        self.dryer_1_off_btn = QtWidgets.QPushButton(parent=self.dryer_page)
        self.dryer_1_off_btn.setGeometry(QtCore.QRect(0, 260, 312, 97))
        self.dryer_1_off_btn.setObjectName("dryer_1_off_btn")
        filamentStacketWidget.addWidget(self.dryer_page)

        self.retranslateUi(filamentStacketWidget)
        QtCore.QMetaObject.connectSlotsByName(filamentStacketWidget)

    def retranslateUi(self, filamentStacketWidget):
        _translate = QtCore.QCoreApplication.translate
        filamentStacketWidget.setWindowTitle(_translate("filamentStacketWidget", "StackedWidget"))
        self.filament_title.setText(_translate("filamentStacketWidget", "Filament"))
        self.filament_title.setProperty("class", _translate("filamentStacketWidget", "title_text"))
        self.change_filament_btn.setText(_translate("filamentStacketWidget", "change\n"
"filament"))
        self.change_filament_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.dryer_btn.setText(_translate("filamentStacketWidget", "dryer"))
        self.dryer_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.unload_btn.setText(_translate("filamentStacketWidget", "unload"))
        self.unload_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_btn.setText(_translate("filamentStacketWidget", "load"))
        self.load_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_pla.setText(_translate("filamentStacketWidget", "PLA"))
        self.load_t1_pla.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_petg.setText(_translate("filamentStacketWidget", "PETG"))
        self.load_t1_petg.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_tpu.setText(_translate("filamentStacketWidget", "TPU"))
        self.load_t1_tpu.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_custom.setText(_translate("filamentStacketWidget", "CUSTOM"))
        self.load_t1_custom.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_nylon.setText(_translate("filamentStacketWidget", "NYLON"))
        self.load_t1_nylon.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_hips.setText(_translate("filamentStacketWidget", "HIPS"))
        self.load_t1_hips.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_abs.setText(_translate("filamentStacketWidget", "ABS"))
        self.load_t1_abs.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t1_title.setText(_translate("filamentStacketWidget", "Load Tool Head 1 "))
        self.load_t1_title.setProperty("class", _translate("filamentStacketWidget", "title_text"))
        self.load_t2_pla.setText(_translate("filamentStacketWidget", "PLA"))
        self.load_t2_pla.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_petg.setText(_translate("filamentStacketWidget", "PETG"))
        self.load_t2_petg.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_abs.setText(_translate("filamentStacketWidget", "ABS"))
        self.load_t2_abs.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_custom.setText(_translate("filamentStacketWidget", "CUSTOM"))
        self.load_t2_custom.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_nylon.setText(_translate("filamentStacketWidget", "NYLON"))
        self.load_t2_nylon.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_hips.setText(_translate("filamentStacketWidget", "HIPS"))
        self.load_t2_hips.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.load_t2_title.setText(_translate("filamentStacketWidget", "Load Tool Head 2"))
        self.load_t2_title.setProperty("class", _translate("filamentStacketWidget", "title_text"))
        self.load_t2_tpu.setText(_translate("filamentStacketWidget", "TPU"))
        self.load_t2_tpu.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.dryer_1_icon.setText(_translate("filamentStacketWidget", "Dryer Icon"))
        self.dryer_2_auto_btn.setText(_translate("filamentStacketWidget", "Auto temperature"))
        self.dryer_2_auto_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.dryer_2_icon.setText(_translate("filamentStacketWidget", "Dryer 2 Icon"))
        self.dryer_1_auto_btn.setText(_translate("filamentStacketWidget", "auto temperature"))
        self.dryer_1_auto_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.dryers_title.setText(_translate("filamentStacketWidget", "Dryers"))
        self.dryers_title.setProperty("class", _translate("filamentStacketWidget", "title_text"))
        self.dryer_2_off_btn.setText(_translate("filamentStacketWidget", "turn off dryer"))
        self.dryer_2_off_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
        self.dryer_1_off_btn.setText(_translate("filamentStacketWidget", "turn off dryer"))
        self.dryer_1_off_btn.setProperty("class", _translate("filamentStacketWidget", "menu_btn"))
