# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/qt_ui/printStackedWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_printStackedWidget(object):
    def setupUi(self, printStackedWidget):
        printStackedWidget.setObjectName("printStackedWidget")
        printStackedWidget.resize(716, 380)
        self.print_page = QtWidgets.QWidget()
        self.print_page.setObjectName("print_page")
        self.layoutWidget = QtWidgets.QWidget(parent=self.print_page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_title = QtWidgets.QLabel(parent=self.layoutWidget)
        self.main_title.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.main_title.setStyleSheet("")
        self.main_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_title.setObjectName("main_title")
        self.verticalLayout.addWidget(self.main_title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.print_btn = CustomQPushButton(parent=self.layoutWidget)
        self.print_btn.setMinimumSize(QtCore.QSize(312, 97))
        font = QtGui.QFont()
        font.setFamily("Momcake-Bold")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.print_btn.setFont(font)
        self.print_btn.setMouseTracking(False)
        self.print_btn.setTabletTracking(True)
        self.print_btn.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.print_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.print_btn.setStyleSheet("#unload_btn {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload.png);\n"
"    image-position: left;\n"
"}\n"
"\n"
"#unload_btn::pressed {\n"
"    image:url(:/General_icons/test_media/icons/filament_unload_PRESSED.png);\n"
"    image-position: left;\n"
"}")
        self.print_btn.setAutoDefault(False)
        self.print_btn.setFlat(True)
        self.print_btn.setProperty("borderLeftPixmap", QtGui.QPixmap(":/button_borders/media/buttons/btn_part1.svg"))
        self.print_btn.setProperty("borderCenterPixmap", QtGui.QPixmap(":/button_borders/media/buttons/btn_part2.svg"))
        self.print_btn.setProperty("borderRightPixmap", QtGui.QPixmap(":/button_borders/media/buttons/btn_part3.svg"))
        self.print_btn.setObjectName("print_btn")
        self.verticalLayout.addWidget(self.print_btn)
        self.main_text_box = QtWidgets.QLabel(parent=self.layoutWidget)
        self.main_text_box.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Momcake")
        font.setPointSize(14)
        self.main_text_box.setFont(font)
        self.main_text_box.setStyleSheet("#main_text_box{\n"
"    align-text: center;\n"
"    font-family: Momcake;\n"
"    font-style: Momcake-Thin;\n"
"    font-size: 14pt;\n"
"    color: white;\n"
"    padding-left: 100px;\n"
"    padding-right: 100px;\n"
"}")
        self.main_text_box.setObjectName("main_text_box")
        self.verticalLayout.addWidget(self.main_text_box, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        printStackedWidget.addWidget(self.print_page)
        self.files_page = QtWidgets.QWidget()
        self.files_page.setObjectName("files_page")
        self.pushButton = QtWidgets.QPushButton(parent=self.files_page)
        self.pushButton.setGeometry(QtCore.QRect(520, 0, 71, 51))
        self.pushButton.setObjectName("pushButton")
        self.select_file_scroll_area = QtWidgets.QScrollArea(parent=self.files_page)
        self.select_file_scroll_area.setGeometry(QtCore.QRect(0, 60, 481, 241))
        self.select_file_scroll_area.setWidgetResizable(True)
        self.select_file_scroll_area.setObjectName("select_file_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.select_file_scroll_area.setWidget(self.scrollAreaWidgetContents)
        printStackedWidget.addWidget(self.files_page)

        self.retranslateUi(printStackedWidget)
        QtCore.QMetaObject.connectSlotsByName(printStackedWidget)

    def retranslateUi(self, printStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        printStackedWidget.setWindowTitle(_translate("printStackedWidget", "StackedWidget"))
        self.main_title.setText(_translate("printStackedWidget", "Filament"))
        self.main_title.setProperty("class", _translate("printStackedWidget", "title_text"))
        self.print_btn.setText(_translate("printStackedWidget", "PRINT"))
        self.print_btn.setProperty("class", _translate("printStackedWidget", "menu_btn"))
        self.main_text_box.setText(_translate("printStackedWidget", "Printer ready to use"))
        self.pushButton.setText(_translate("printStackedWidget", "Back"))
        self.pushButton.setProperty("class", _translate("printStackedWidget", "back_btn"))
from qt_ui.ui_util import CustomQPushButton
