# Form implementation generated from reading ui file '/home/bugo/github/Blocks_Screen/qt_ui/utilitiesStackedWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_utilitiesStackedWidget(object):
    def setupUi(self, utilitiesStackedWidget):
        utilitiesStackedWidget.setObjectName("utilitiesStackedWidget")
        utilitiesStackedWidget.resize(400, 300)
        self.utilities_page = QtWidgets.QWidget()
        self.utilities_page.setObjectName("utilities_page")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.utilities_page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 684, 371))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.utilities_grid = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.utilities_grid.setContentsMargins(0, 0, 0, 0)
        self.utilities_grid.setVerticalSpacing(0)
        self.utilities_grid.setObjectName("utilities_grid")
        self.utilities_btns_grid = QtWidgets.QGridLayout()
        self.utilities_btns_grid.setContentsMargins(-1, 0, -1, -1)
        self.utilities_btns_grid.setSpacing(0)
        self.utilities_btns_grid.setObjectName("utilities_btns_grid")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.utilities_btns_grid.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.utilities_btns_grid.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.utilities_btns_grid.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.utilities_btns_grid.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.utilities_btns_grid.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.utilities_btns_grid.addWidget(self.pushButton_15, 1, 1, 1, 1)
        self.utilities_grid.addLayout(self.utilities_btns_grid, 1, 0, 1, 1)
        self.utilities_title = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.utilities_title.setStyleSheet("")
        self.utilities_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.utilities_title.setObjectName("utilities_title")
        self.utilities_grid.addWidget(self.utilities_title, 0, 0, 1, 1)
        utilitiesStackedWidget.addWidget(self.utilities_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 110, 312, 97))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 312, 97))
        self.pushButton_2.setObjectName("pushButton_2")
        utilitiesStackedWidget.addWidget(self.page)

        self.retranslateUi(utilitiesStackedWidget)
        QtCore.QMetaObject.connectSlotsByName(utilitiesStackedWidget)

    def retranslateUi(self, utilitiesStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        utilitiesStackedWidget.setWindowTitle(_translate("utilitiesStackedWidget", "StackedWidget"))
        self.pushButton_10.setText(_translate("utilitiesStackedWidget", "Axes\n"
"Maintenance"))
        self.pushButton_10.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_11.setText(_translate("utilitiesStackedWidget", "Routine\n"
"Check"))
        self.pushButton_11.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_12.setText(_translate("utilitiesStackedWidget", "Factory Reset"))
        self.pushButton_12.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_13.setText(_translate("utilitiesStackedWidget", "LEDs"))
        self.pushButton_13.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_14.setText(_translate("utilitiesStackedWidget", "Info"))
        self.pushButton_14.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_15.setText(_translate("utilitiesStackedWidget", "LCD Settings"))
        self.pushButton_15.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.utilities_title.setText(_translate("utilitiesStackedWidget", "Utilities"))
        self.utilities_title.setProperty("class", _translate("utilitiesStackedWidget", "title_text"))
        self.pushButton_3.setText(_translate("utilitiesStackedWidget", "PushButton"))
        self.pushButton_3.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
        self.pushButton_2.setText(_translate("utilitiesStackedWidget", "LEDs"))
        self.pushButton_2.setProperty("class", _translate("utilitiesStackedWidget", "menu_btn"))
