"""Off-thread gcode header parsing: embedded thumbnails + client-side metadata (USB)."""

from __future__ import annotations

import base64
import binascii
import logging
import re
from collections import OrderedDict
from collections.abc import Callable

from PyQt6 import QtCore, QtGui

logger = logging.getLogger(__name__)

# --- Thumbnail parsing -------------------------------------------------------

# Matches PrusaSlicer/Cura "thumbnail begin" and the Creality "png begin" variant.
_THUMBNAIL_RE = re.compile(
    r"; (?:thumbnail|png) begin (\d+)[x*](\d+) \d+\s*\n(.*?); (?:thumbnail|png) end",
    re.DOTALL,
)


def parse_embedded_thumbnail(header: bytes) -> bytes | None:
    """Return PNG bytes of the largest thumbnail embedded in a gcode header."""
    text = header.decode("latin-1", errors="ignore")
    best_area = -1
    best_block = None
    for width, height, block in _THUMBNAIL_RE.findall(text):
        area = int(width) * int(height)
        if area > best_area:
            best_area, best_block = area, block
    if best_block is None:
        return None
    b64 = "".join(line.strip().lstrip(";").strip() for line in best_block.splitlines())
    try:
        return base64.b64decode(b64)
    except (ValueError, binascii.Error):
        return None


# --- Metadata parsing --------------------------------------------------------

# Slicer footer/header comments use "; key = value" (Orca/Prusa/Super) or "; key: value".
_KV_RE = re.compile(r"^;+\s*([^=:\n]+?)\s*[=:]\s*(.+?)\s*$", re.MULTILINE)
# Cura banner: ";Generated with Cura_SteamEngine 5.6.0".
_CURA_RE = re.compile(r"generated with cura[_ ]?\w*\s+([\d.]+)", re.IGNORECASE)
# Orca/Prusa/Super banner: "; generated by OrcaSlicer 2.3.2 ...".
_BANNER_RE = re.compile(r"generated by\s+(\S+)\s+([\d.]+)", re.IGNORECASE)
_TIME_UNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}


def _to_float(value: str) -> float | None:
    """First float in a string, or None."""
    match = re.search(r"-?\d+(?:\.\d+)?", value)
    return float(match.group()) if match else None


def _to_int(value: str) -> int | None:
    """First int in a string, or None."""
    match = re.search(r"-?\d+", value)
    return int(match.group()) if match else None


def _parse_time(value: str) -> int | None:
    """Seconds from "1h 20m 2s"-style or a bare seconds count (Cura ;TIME:)."""
    parts = re.findall(r"(\d+)\s*([dhms])", value.lower())
    if parts:
        return sum(int(n) * _TIME_UNITS[u] for n, u in parts)
    return _to_int(value)


def _unquote(value: str) -> str:
    """Slicer values are often quoted."""
    return value.strip('"')


def _first_token(value: str) -> str:
    """First entry of a possibly multi-extruder ";"-separated value."""
    return value.strip('"').split(";")[0].strip()


# Slicer comment key -> (output field, converter); first alias present wins.
_FIELD_ALIASES: dict[str, tuple[str, Callable[[str], object | None]]] = {
    "estimated printing time (normal mode)": ("estimated_time", _parse_time),
    "estimated printing time": ("estimated_time", _parse_time),
    "time": ("estimated_time", _parse_time),
    "filament used [mm]": ("filament_total", _to_float),
    "filament used": ("filament_total", _to_float),
    "total filament used [g]": ("filament_weight_total", _to_float),
    "filament used [g]": ("filament_weight_total", _to_float),
    "total layers count": ("layer_count", _to_int),
    "layer_count": ("layer_count", _to_int),
    "max_z_height": ("object_height", _to_float),
    "object_height": ("object_height", _to_float),
    "maxz": ("object_height", _to_float),
    "filament_type": ("filament_type", _first_token),
    "filament used type": ("filament_type", _first_token),
    "filament_settings_id": ("filament_name", _unquote),
    "filament_name": ("filament_name", _unquote),
    "nozzle_diameter": ("nozzle_diameter", _to_float),
    "layer_height": ("layer_height", _to_float),
    "first_layer_height": ("first_layer_height", _to_float),
    "first_layer_temperature": ("first_layer_extr_temp", _to_float),
    "first_layer_extruder_temp": ("first_layer_extr_temp", _to_float),
    "first_layer_bed_temperature": ("first_layer_bed_temp", _to_float),
    "first_layer_bed_temp": ("first_layer_bed_temp", _to_float),
}


def parse_gcode_metadata(header: bytes, footer: bytes) -> dict:
    """Moonraker-shaped metadata dict parsed from a gcode header + footer blob."""
    text = (
        header.decode("latin-1", "ignore") + "\n" + footer.decode("latin-1", "ignore")
    )
    kv = {k.strip().lower(): v.strip() for k, v in _KV_RE.findall(text)}
    meta: dict = {}

    for alias, (out_key, convert) in _FIELD_ALIASES.items():
        if out_key in meta or alias not in kv:
            continue
        if (value := convert(kv[alias])) is not None:
            meta[out_key] = value

    if (banner := _BANNER_RE.search(text)) is not None:
        meta["slicer"], meta["slicer_version"] = banner.group(1), banner.group(2)
    elif (cura := _CURA_RE.search(text)) is not None:
        meta["slicer"], meta["slicer_version"] = "Cura", cura.group(1)

    return meta


# --- Off-thread loaders ------------------------------------------------------


def _fetch_thumbnail(rest, gcode_path: str) -> QtGui.QImage | None:
    """Range-fetch a gcode header and decode its embedded thumbnail."""
    header = rest.get_gcode_header(gcode_path)
    png = parse_embedded_thumbnail(header) if header else None
    if not png:
        return None
    image = QtGui.QImage()
    return image if image.loadFromData(png, "PNG") and not image.isNull() else None


def _fetch_metadata(rest, gcode_path: str) -> dict:
    """Range-fetch both ends of a gcode and parse its slicer metadata."""
    header = rest.get_gcode_header(gcode_path) or b""
    footer = rest.get_gcode_tail(gcode_path) or b""
    return parse_gcode_metadata(header, footer) if (header or footer) else {}


class _LoaderSignals(QtCore.QObject):
    """Carries a worker result back to the UI thread (QRunnable can't hold signals)."""

    result = QtCore.pyqtSignal(str, object)  # (gcode_path, payload)


class _FetchTask(QtCore.QRunnable):
    """Runs one loader's fetch + parse for a single gcode off the UI thread."""

    def __init__(self, rest, gcode_path: str, fetch, signals: _LoaderSignals) -> None:
        super().__init__()
        self._rest = rest
        self._gcode_path = gcode_path
        self._fetch = fetch
        self._signals = signals

    @QtCore.pyqtSlot()
    def run(self) -> None:
        """Fetch in the worker; the loader caches + re-emits on the UI thread."""
        try:
            payload = self._fetch(self._rest, self._gcode_path)
        except Exception:  # a bad file must not kill the pool thread
            logger.exception("gcode fetch failed for %s", self._gcode_path)
            payload = None
        self._signals.result.emit(self._gcode_path, payload)


class _GcodeLoader(QtCore.QObject):
    """Serves parsed gcode data via a capped thread pool + bounded LRU cache."""

    _CACHE_MAX = 32
    _fetch = staticmethod(_fetch_thumbnail)

    def __init__(self, rest, parent: QtCore.QObject | None = None) -> None:
        super().__init__(parent)
        self._rest = rest
        self._pool = QtCore.QThreadPool(self)
        self._pool.setMaxThreadCount(2)  # bound concurrent fetches on the 2GB Pi
        self._cache: OrderedDict[str, object] = OrderedDict()
        self._inflight: set[str] = set()
        self._signals = _LoaderSignals()
        self._signals.result.connect(self._on_result)

    def cached(self, gcode_path: str):
        """Return an already-fetched payload (promoted to MRU), or None."""
        payload = self._cache.get(gcode_path)
        if payload is not None:
            self._cache.move_to_end(gcode_path)
        return payload

    def request(self, gcode_path: str) -> None:
        """Fetch off-thread; emits ready() once the payload is available."""
        cached = self.cached(gcode_path)
        if cached is not None:
            self.ready.emit(gcode_path, cached)
            return
        if not gcode_path or self._rest is None or gcode_path in self._inflight:
            return
        self._inflight.add(gcode_path)
        self._pool.start(_FetchTask(self._rest, gcode_path, self._fetch, self._signals))

    def _on_result(self, gcode_path: str, payload: object) -> None:
        """Cache the payload (LRU-bounded) and notify listeners."""
        self._inflight.discard(gcode_path)
        if payload is None or payload == {}:
            return
        if len(self._cache) >= self._CACHE_MAX:
            self._cache.popitem(last=False)
        self._cache[gcode_path] = payload
        self.ready.emit(gcode_path, payload)


class ThumbnailLoader(_GcodeLoader):
    """Embedded gcode thumbnails, decoded off the UI thread."""

    ready = QtCore.pyqtSignal(str, object)  # (gcode_path, QImage)

    _CACHE_MAX = 32
    _fetch = staticmethod(_fetch_thumbnail)

    request_embedded = _GcodeLoader.request


class GcodeMetadataLoader(_GcodeLoader):
    """Client-parsed metadata for gcodes Moonraker cannot scan (USB)."""

    ready = QtCore.pyqtSignal(str, dict)  # (gcode_path, metadata)

    _CACHE_MAX = 64
    _fetch = staticmethod(_fetch_metadata)


# --- Shared module singletons ------------------------------------------------

_thumb_loader: ThumbnailLoader | None = None
_meta_loader: GcodeMetadataLoader | None = None


def configure(rest) -> ThumbnailLoader:
    """Create the shared thumbnail loader from a MoonRest client (call once at startup)."""
    global _thumb_loader
    _thumb_loader = ThumbnailLoader(rest)
    return _thumb_loader


def get_loader() -> ThumbnailLoader | None:
    """Return the shared thumbnail loader, or None if not configured yet."""
    return _thumb_loader


def configure_metadata(rest) -> GcodeMetadataLoader:
    """Create the shared metadata loader from a MoonRest client (call once at startup)."""
    global _meta_loader
    _meta_loader = GcodeMetadataLoader(rest)
    return _meta_loader


def get_metadata_loader() -> GcodeMetadataLoader | None:
    """Return the shared metadata loader, or None if not configured yet."""
    return _meta_loader


def cached_pixmap(gcode_path: str) -> QtGui.QPixmap | None:
    """Cached embedded thumbnail as a main-thread QPixmap; queues a fetch on miss."""
    loader = _thumb_loader
    gcode_path = gcode_path.removeprefix("/")
    if loader is None or not gcode_path:
        return None
    image = loader.cached(gcode_path)
    if image is None:
        loader.request_embedded(gcode_path)
        return None
    return QtGui.QPixmap.fromImage(image) if not image.isNull() else None
