"""Off-thread gcode header parsing: embedded thumbnails + client-side metadata (USB)."""

from __future__ import annotations

import base64
import binascii
import logging
import re
from collections import OrderedDict

from PyQt6 import QtCore, QtGui

logger = logging.getLogger(__name__)

# --- Thumbnail parsing -------------------------------------------------------

# Matches PrusaSlicer/Cura "thumbnail begin" and the Creality "png begin" variant.
_THUMBNAIL_RE = re.compile(
    r"; (?:thumbnail|png) begin (\d+)[x*](\d+) \d+\s*\n(.*?); (?:thumbnail|png) end",
    re.DOTALL,
)


def parse_embedded_thumbnail(header: bytes) -> bytes | None:
    """Return PNG bytes of the largest thumbnail embedded in a gcode header."""
    text = header.decode("latin-1", errors="ignore")
    best_area = -1
    best_block = None
    for width, height, block in _THUMBNAIL_RE.findall(text):
        area = int(width) * int(height)
        if area > best_area:
            best_area, best_block = area, block
    if best_block is None:
        return None
    b64 = "".join(line.strip().lstrip(";").strip() for line in best_block.splitlines())
    try:
        return base64.b64decode(b64)
    except (ValueError, binascii.Error):
        return None


# --- Metadata parsing --------------------------------------------------------

# Slicer footer/header comments use "; key = value" (Orca/Prusa/Super) or "; key: value".
_KV_RE = re.compile(r"^;+\s*([^=:\n]+?)\s*[=:]\s*(.+?)\s*$", re.MULTILINE)
# Cura banner: ";Generated with Cura_SteamEngine 5.6.0".
_CURA_RE = re.compile(r"generated with cura[_ ]?\w*\s+([\d.]+)", re.IGNORECASE)
# Orca/Prusa/Super banner: "; generated by OrcaSlicer 2.3.2 ...".
_BANNER_RE = re.compile(r"generated by\s+(\S+)\s+([\d.]+)", re.IGNORECASE)
_TIME_UNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}


def _to_float(value: str) -> float | None:
    """First float in a string, or None."""
    match = re.search(r"-?\d+(?:\.\d+)?", value)
    return float(match.group()) if match else None


def _to_int(value: str) -> int | None:
    """First int in a string, or None."""
    match = re.search(r"-?\d+", value)
    return int(match.group()) if match else None


def _parse_time(value: str) -> int | None:
    """Seconds from "1h 20m 2s"-style or a bare seconds count (Cura ;TIME:)."""
    parts = re.findall(r"(\d+)\s*([dhms])", value.lower())
    if parts:
        return sum(int(n) * _TIME_UNITS[u] for n, u in parts)
    return _to_int(value)


def parse_gcode_metadata(header: bytes, footer: bytes) -> dict:
    """Moonraker-shaped metadata dict parsed from a gcode header + footer blob."""
    text = (
        header.decode("latin-1", "ignore") + "\n" + footer.decode("latin-1", "ignore")
    )
    kv = {k.strip().lower(): v.strip() for k, v in _KV_RE.findall(text)}
    meta: dict = {}

    def first(*keys: str) -> str | None:
        for key in keys:
            if key in kv:
                return kv[key]
        return None

    if (
        raw := first(
            "estimated printing time (normal mode)", "estimated printing time", "time"
        )
    ) is not None:
        if (secs := _parse_time(raw)) is not None:
            meta["estimated_time"] = secs
    if (raw := first("filament used [mm]", "filament used")) is not None:
        if (mm := _to_float(raw)) is not None:
            meta["filament_total"] = mm
    if (raw := first("total filament used [g]", "filament used [g]")) is not None:
        if (grams := _to_float(raw)) is not None:
            meta["filament_weight_total"] = grams
    if (raw := first("total layers count", "layer_count")) is not None:
        if (count := _to_int(raw)) is not None:
            meta["layer_count"] = count
    if (raw := first("max_z_height", "object_height", "maxz")) is not None:
        if (height := _to_float(raw)) is not None:
            meta["object_height"] = height
    if (raw := first("filament_type", "filament used type")) is not None:
        meta["filament_type"] = raw.strip('"').split(";")[0].strip()
    if (raw := first("filament_settings_id", "filament_name")) is not None:
        meta["filament_name"] = raw.strip('"')
    if (raw := first("nozzle_diameter")) is not None:
        if (dia := _to_float(raw)) is not None:
            meta["nozzle_diameter"] = dia
    if (raw := first("layer_height")) is not None:
        if (lh := _to_float(raw)) is not None:
            meta["layer_height"] = lh
    if (raw := first("first_layer_height")) is not None:
        if (flh := _to_float(raw)) is not None:
            meta["first_layer_height"] = flh
    if (
        raw := first("first_layer_temperature", "first_layer_extruder_temp")
    ) is not None:
        if (temp := _to_float(raw)) is not None:
            meta["first_layer_extruder_temp"] = temp
    if (
        raw := first("first_layer_bed_temperature", "first_layer_bed_temp")
    ) is not None:
        if (temp := _to_float(raw)) is not None:
            meta["first_layer_bed_temp"] = temp
    if (raw := first("chamber_temperature", "chamber_temp")) is not None:
        if (temp := _to_float(raw)) is not None:
            meta["chamber_temp"] = temp

    if (banner := _BANNER_RE.search(text)) is not None:
        meta["slicer"], meta["slicer_version"] = banner.group(1), banner.group(2)
    elif (cura := _CURA_RE.search(text)) is not None:
        meta["slicer"], meta["slicer_version"] = "Cura", cura.group(1)

    return meta


# --- Thumbnail loader --------------------------------------------------------


class _ThumbnailSignals(QtCore.QObject):
    """Carries a worker result back to the UI thread (QRunnable can't hold signals)."""

    result = QtCore.pyqtSignal(str, object)  # (gcode_path, QImage | None)


class _EmbeddedThumbnailTask(QtCore.QRunnable):
    """Fetches + parses one gcode's embedded thumbnail off the UI thread."""

    def __init__(self, rest, gcode_path: str, signals: _ThumbnailSignals) -> None:
        super().__init__()
        self._rest = rest
        self._gcode_path = gcode_path
        self._signals = signals

    @QtCore.pyqtSlot()
    def run(self) -> None:
        """Decode to QImage in the worker; the slot converts to pixmap on the UI thread."""
        image = None
        header = self._rest.get_gcode_header(self._gcode_path)
        if header:
            png = parse_embedded_thumbnail(header)
            if png:
                candidate = QtGui.QImage()
                if candidate.loadFromData(png, "PNG") and not candidate.isNull():
                    image = candidate
        self._signals.result.emit(self._gcode_path, image)


class ThumbnailLoader(QtCore.QObject):
    """Serves embedded gcode thumbnails via a capped thread pool + bounded LRU cache."""

    ready = QtCore.pyqtSignal(str, object)  # (gcode_path, QImage)

    _CACHE_MAX = 32

    def __init__(self, rest, parent: QtCore.QObject | None = None) -> None:
        super().__init__(parent)
        self._rest = rest
        self._pool = QtCore.QThreadPool(self)
        self._pool.setMaxThreadCount(2)  # bound concurrent decodes on the 2GB Pi
        self._cache: OrderedDict[str, QtGui.QImage] = OrderedDict()
        self._inflight: set[str] = set()
        self._signals = _ThumbnailSignals()
        self._signals.result.connect(self._on_result)

    def cached(self, gcode_path: str) -> QtGui.QImage | None:
        """Return an already-fetched thumbnail (promoted to MRU), or None."""
        image = self._cache.get(gcode_path)
        if image is not None:
            self._cache.move_to_end(gcode_path)
        return image

    def request_embedded(self, gcode_path: str) -> None:
        """Fetch a gcode's embedded thumbnail off-thread; emits ready() when available."""
        cached = self.cached(gcode_path)
        if cached is not None:
            self.ready.emit(gcode_path, cached)
            return
        if not gcode_path or self._rest is None or gcode_path in self._inflight:
            return
        self._inflight.add(gcode_path)
        self._pool.start(_EmbeddedThumbnailTask(self._rest, gcode_path, self._signals))

    def _on_result(self, gcode_path: str, image: object) -> None:
        """Cache the decoded image (LRU-bounded) and notify listeners."""
        self._inflight.discard(gcode_path)
        if image is None:
            return
        if len(self._cache) >= self._CACHE_MAX:
            self._cache.popitem(last=False)
        self._cache[gcode_path] = image
        self.ready.emit(gcode_path, image)


# --- Metadata loader ---------------------------------------------------------


class _MetadataSignals(QtCore.QObject):
    """Carries a worker result back to the UI thread (QRunnable can't hold signals)."""

    result = QtCore.pyqtSignal(str, dict)  # (gcode_path, metadata)


class _MetadataTask(QtCore.QRunnable):
    """Fetches a gcode's header + footer and parses its metadata off the UI thread."""

    def __init__(self, rest, gcode_path: str, signals: _MetadataSignals) -> None:
        super().__init__()
        self._rest = rest
        self._gcode_path = gcode_path
        self._signals = signals

    @QtCore.pyqtSlot()
    def run(self) -> None:
        """Range-fetch both ends of the file, parse, and emit the metadata dict."""
        header = self._rest.get_gcode_header(self._gcode_path) or b""
        footer = self._rest.get_gcode_tail(self._gcode_path) or b""
        meta = parse_gcode_metadata(header, footer) if (header or footer) else {}
        self._signals.result.emit(self._gcode_path, meta)


class GcodeMetadataLoader(QtCore.QObject):
    """Serves client-parsed gcode metadata via a capped thread pool + bounded LRU cache."""

    ready = QtCore.pyqtSignal(str, dict)  # (gcode_path, metadata)

    _CACHE_MAX = 64

    def __init__(self, rest, parent: QtCore.QObject | None = None) -> None:
        super().__init__(parent)
        self._rest = rest
        self._pool = QtCore.QThreadPool(self)
        self._pool.setMaxThreadCount(2)  # bound concurrent fetches on the 2GB Pi
        self._cache: OrderedDict[str, dict] = OrderedDict()
        self._inflight: set[str] = set()
        self._signals = _MetadataSignals()
        self._signals.result.connect(self._on_result)

    def request(self, gcode_path: str) -> None:
        """Fetch + parse a gcode's metadata off-thread; emits ready() when available."""
        cached = self._cache.get(gcode_path)
        if cached is not None:
            self._cache.move_to_end(gcode_path)
            self.ready.emit(gcode_path, cached)
            return
        if not gcode_path or self._rest is None or gcode_path in self._inflight:
            return
        self._inflight.add(gcode_path)
        self._pool.start(_MetadataTask(self._rest, gcode_path, self._signals))

    def _on_result(self, gcode_path: str, meta: dict) -> None:
        """Cache the parsed metadata (LRU-bounded) and notify listeners."""
        self._inflight.discard(gcode_path)
        if not meta:
            return
        if len(self._cache) >= self._CACHE_MAX:
            self._cache.popitem(last=False)
        self._cache[gcode_path] = meta
        self.ready.emit(gcode_path, meta)


# --- Shared module singletons ------------------------------------------------

_thumb_loader: ThumbnailLoader | None = None
_meta_loader: GcodeMetadataLoader | None = None


def configure(rest) -> ThumbnailLoader:
    """Create the shared thumbnail loader from a MoonRest client (call once at startup)."""
    global _thumb_loader
    _thumb_loader = ThumbnailLoader(rest)
    return _thumb_loader


def get_loader() -> ThumbnailLoader | None:
    """Return the shared thumbnail loader, or None if not configured yet."""
    return _thumb_loader


def configure_metadata(rest) -> GcodeMetadataLoader:
    """Create the shared metadata loader from a MoonRest client (call once at startup)."""
    global _meta_loader
    _meta_loader = GcodeMetadataLoader(rest)
    return _meta_loader


def get_metadata_loader() -> GcodeMetadataLoader | None:
    """Return the shared metadata loader, or None if not configured yet."""
    return _meta_loader


def cached_pixmap(gcode_path: str) -> QtGui.QPixmap | None:
    """Cached embedded thumbnail as a main-thread QPixmap; queues a fetch on miss."""
    loader = _thumb_loader
    gcode_path = gcode_path.removeprefix("/")
    if loader is None or not gcode_path:
        return None
    image = loader.cached(gcode_path)
    if image is None:
        loader.request_embedded(gcode_path)
        return None
    return QtGui.QPixmap.fromImage(image) if not image.isNull() else None
