#!/usr/bin/env python3 -S
"""Boot-time splash holder for tty8.

Activates tty8 immediately at boot (VT switch does not require fb0), then
polls for /dev/fb0 and writes the cached splash once it becomes available.

On Pi 5 KMS, dev-fb0 appears ~90 s after boot; using it as a systemd unit
dependency (Wants/After=dev-fb0.device) delays the service past the point
where the terminal is already visible.  We start as soon as local-fs is up,
switch VT immediately, and write to fb0 as soon as it arrives.

KDSETMODE is intentionally NOT called: setting tty8 to KD_GRAPHICS+VT_AUTO
would cause VT_ACTIVATE(7) to return -EINVAL when bs-splash.py tries to switch
FROM tty8 at startup.

Handles SIGUSR1 to re-read the cache after bs-splash.py updates it.
"""

import fcntl
import json
import os
import signal
import sys
import time

_CACHE = "/home/blocks/.cache/blockscreen/splash.raw"
_FB0 = "/dev/fb0"
_VT_ACTIVATE = 0x5606
_VT_WAITACTIVE = 0x5607
_VT_NUM = 8
_FB0_POLL_TIMEOUT = 20.0
_FB0_POLL_INTERVAL = 0.25
_STATUS_PATH = "/run/blockscreen/updater_status.json"

_running = True
_status_mtime: float = 0.0


def _log(msg: str) -> None:
    sys.stderr.write(f"bs-splash-holder: {msg}\n")
    sys.stderr.flush()


def _activate_tty8() -> None:
    for dev in ("/dev/tty0", "/dev/console"):
        try:
            fd = os.open(dev, os.O_WRONLY | os.O_NOCTTY)
            fcntl.ioctl(fd, _VT_ACTIVATE, _VT_NUM)
            try:
                fcntl.ioctl(fd, _VT_WAITACTIVE, _VT_NUM)
            except OSError:
                pass
            os.close(fd)
            _log(f"tty{_VT_NUM} activated via {dev}")
            return
        except OSError as e:
            _log(f"VT_ACTIVATE {_VT_NUM} on {dev} failed: {e}")


def _write_splash() -> None:
    try:
        if os.path.exists(_CACHE):
            with (
                open(_CACHE, "rb", buffering=0) as src,
                open(_FB0, "wb", buffering=0) as dst,
            ):
                dst.write(src.read())
    except OSError as e:
        _log(f"fb0 write failed: {e}")


def _wait_for_fb0(timeout: float = _FB0_POLL_TIMEOUT) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if os.path.exists(_FB0):
            return True
        time.sleep(_FB0_POLL_INTERVAL)
    _log(f"/dev/fb0 not available after {timeout:.0f}s")
    return False


def _show_update_status() -> None:
    try:
        with open(_STATUS_PATH) as _f:
            s = json.load(_f)
        msg = f"  Updating {s['name']}… step {s['step']}/{s['total']}".encode()
        with open("/dev/tty8", "wb") as _tty:
            _tty.write(b"\x1b[20;1H\x1b[2K" + msg)
    except (OSError, KeyError, ValueError):
        pass


def _on_sigusr1(_sig: int, _frame: object) -> None:
    _write_splash()


def _on_sigterm(_sig: int, _frame: object) -> None:
    global _running
    _running = False


signal.signal(signal.SIGUSR1, _on_sigusr1)
signal.signal(signal.SIGTERM, _on_sigterm)

# Switch to tty8 immediately — VT switch does not require fb0.
_activate_tty8()

# Write text immediately so tty8 is not blank while waiting for fb0/splash.
try:
    with open("/dev/tty8", "wb") as _tty:
        # clear screen, home cursor, hide cursor
        _tty.write(b"\x1b[2J\x1b[H\x1b[?25l  BlocksScreen loading...")
except OSError:
    pass

# Wait for fb0 (Pi 5 KMS initialises it ~90 s into boot).
if _wait_for_fb0():
    # splash.raw is generated by bs-splash.py at xorg startup; wait for it.
    _raw_deadline = time.monotonic() + 60.0
    while time.monotonic() < _raw_deadline:
        if os.path.exists(_CACHE):
            _write_splash()
            break
        time.sleep(0.5)

while _running:
    try:
        mtime = os.stat(_STATUS_PATH).st_mtime
        if mtime != _status_mtime:
            _status_mtime = mtime
            _show_update_status()
    except OSError:
        pass
    time.sleep(1)
